# Módulo 01: Fundamentos de Programação
>
> [Universidade Federal do Ceará (UFC)](https://www.ufc.br/)\
> [Departamento de Computação (DC)](https://dc.ufc.br/pt/)\
> [Capacitação Técnica e Empreendedora em IA (CTE-IA)](https://www.cteia.dc.ufc.br/)\
> Fase I: Capacitação Teórica de IA\
> Disciplina: Programação para Ciência de Dados (60h)\
> Professor: [Lincoln S. Rocha](http://lattes.cnpq.br/0656977742590515)\
> E-mail: <lincoln@dc.ufc.br>
>

O principal objetivo deste módulo é apresentar os conceitos fundamentais da programação usando a linguagem Python. Este módulo cobrirá o seguinte conteúdo:

1. Programação com uma Forma de Pensar
2. Variáveis e Comandos
3. Funções
4. Condicionais e Recursão
5. Strings e Expressões Regulares
6. Listas, Dicionários e Tuplas
7. Módulos e Pacotes
8. Orientação a Objetos

## 1. Programação como uma Forma de Pensar

 O primeiro objetivo deste módulo é ensinar você a programar em Python. Mas aprender a programar significa aprender uma nova maneira de pensar, então o segundo objetivo deste módulo é ajudá-lo a pensar como um cientista da computação. Essa maneira de pensar combina algumas das melhores características da matemática, engenharia e ciências naturais. Assim como os matemáticos, os cientistas da computação usam linguagens formais para denotar ideias – especificamente cálculos. Como engenheiros, eles projetam coisas, montando componentes em sistemas e avaliando compensações entre alternativas. Como cientistas, eles observam o comportamento de sistemas complexos, formulam hipóteses e testam previsões. Vamos começar com os elementos mais básicos da programação e avançaremos até os conceitos mais complexos. Nesta seção, veremos como Python representa números, letras e palavras. E você aprenderá a realizar operações aritméticas.

### 1.1. Operadores Aritiméticos

Um **operador aritmético** é um símbolo que representa um cálculo aritmético. Por exemplo, o sinal de mais, `+`, realiza uma adição.

In [1]:
10 + 3

13

O sinal de menos, `-`, é o operador utilizado para designar a subtração.

In [2]:
10 - 3

7

O sinal de esterisco, `*`, designa a multiplicação.

In [3]:
10 * 3

30

A barra, `/`, é utilizado para designar a divisão.

In [4]:
10 / 2

5.0

Para obter o resto da divisão, utiliza-se o operador `%`.

In [5]:
10 % 2

0

Observe que o resultado da divisão é `5.0` em vez de `5`. Isso ocorre porque existem dois tipos de números em Python:

- **inteiros**, que representam números sem parte fracionária ou decimal, e
- **números de ponto flutuante**, que representam números inteiros e números com ponto decimal.

Se você adicionar, subtrair ou multiplicar dois números inteiros, o resultado será um número inteiro. Mas se você dividir dois números inteiros, o resultado será um número de ponto flutuante. Python fornece outro operador, `//`, para realizar a divisão de números inteiros. O resultado da divisão de números inteiros é sempre um número inteiro.

In [9]:
10 // 2

5

Por fim, o operador `**` realiza a exponenciação; ou seja, eleva um número a uma potência.

In [10]:
10 ** 2

100

Resumo dos operadores aritiméticos:
| Símbolo | Nome            |
|:-------:|-----------------|
| `+`     | Soma            |
| `-`     | Subtração       | 
| `*`     | Multiplicação   |
| `/`     | Divisão         |
| `%`     | Resto da Divisão|
| `**`    | Exponenciação   | 
| `//`    | Divisão Inteira |

Existem outros operadores aritiméticos: `<< `, `>>`, `&`, `|`, `~` e `^`. Todos esses operadores têm algo em comum: são operadores "bit a bit". Ou seja, operam com números (normalmente), mas em vez de tratar esse número como se fosse um único valor, tratam-no como se fosse uma sequência de bits, escrita em binário em complemento de dois. Porém, não trataremos desses operadores no escopo desse curso. Você pode obter mais inforações na documentação oficial do [Python](https://wiki.python.org/moin/BitwiseOperators).

### 1.2. Expressões

Uma coleção de operadores e números é chamada de expressão. Uma expressão pode conter qualquer número de operadores e números. Por exemplo, aqui está uma expressão que contém dois operadores.

In [11]:
3 + 3 ** 2

12

Observe que a exponenciação ocorre antes da adição. Python segue a ordem de operações que você provavelmente aprendeu em uma aula de matemática: a exponenciação ocorre antes da multiplicação e da divisão, que ocorrem antes da adição e da subtração.

No exemplo a seguir, a multiplicação ocorre antes da adição.

In [12]:
12 + 5 * 6

42

Se você quiser que a adição aconteça primeiro, você pode usar parênteses.

In [13]:
(12 + 5) * 6

102

**Cada expressão** tem um **valor** associado. Por exemplo, a expressão `6 * 7` tem o valor `42`.

### 1.3. Funções Aritiméticas

Além dos operadores aritméticos, Python oferece algumas funções que trabalham com números. Por exemplo, a função `round` pega um número de ponto flutuante e o arredonda para o inteiro mais próximo.

In [14]:
round(10.4)

10

In [15]:
round(10.6)

11

A função `abs` calcula o valor absoluto de um número. Para um número positivo, o valor absoluto é o próprio número.

In [16]:
abs(10.4)

10.4

Para um número negativo, o valor absoluto é positivo.

In [17]:
abs(-10.4)

10.4

Quando usamos uma função como esta, dizemos que estamos **chamando** a função. Uma expressão que chama uma função é uma **chamada de função**.

Quando você chama uma função, os parênteses são obrigatórios. Se você os omitir, receberá uma mensagem de erro.

In [18]:
abs 10.4

SyntaxError: invalid syntax (2532643846.py, line 1)

Você pode ignorar a primeira linha desta mensagem; ela não contém nenhuma informação que precisamos entender agora. A segunda linha é o código que contém o erro, com um acento circunflexo (`^`) abaixo para indicar onde o erro foi descoberto.

A última linha indica que se trata de um erro de sintaxe, o que significa que há algo errado com a estrutura da expressão. Neste exemplo, o problema é que uma chamada de função requer parênteses.

Vamos ver o que acontece se você omitir os parênteses e o valor.

In [19]:
abs

<function abs(x, /)>

Um nome de função por si só é uma expressão legal que possui um valor. Quando exibido, o valor indica que abs é uma função e inclui algumas informações adicionais.

### 1.4. Strings

Além de números, Python também pode representar sequências de letras, que são chamadas de strings porque as letras estão encadeadas como contas em um colar. Para escrever uma string, podemos colocar uma sequência de letras entre aspas retas.

In [20]:
'Ola'

'Ola'

Também é permitido usar aspas duplas.

In [21]:
"Ola"

'Ola'

Aspas duplas facilitam a escrita de uma string que contém um apóstrofo, que é o mesmo símbolo de uma aspa reta.

In [22]:
"olho d'água"

"olho d'água"

Strings também podem conter espaços, pontuação e dígitos.

In [23]:
"Bem, "

'Bem, '

O operador `+` funciona com strings; ele une (concatena) duas strings em uma única string, o que é chamado de concatenação.

In [24]:
"Bem, " + "esse é um mundo " + "pequeno!"

'Bem, esse é um mundo pequeno!'

O operador `*` também funciona com strings; ele faz várias cópias de uma string e as concatena.

In [25]:
"ola, " * 4

'ola, ola, ola, ola, '

Os outros operadores aritméticos não funcionam com strings.

O Python fornece uma função chamada `len` que calcula o comprimento de uma string.

In [26]:
len("Ola mundo!")

10

Observe que len conta as letras entre aspas, mas não as aspas.

Ao criar uma string, certifique-se de usar aspas retas. As aspas posteriores, também conhecidas como crase, causam um erro de sintaxe.

In [27]:
`Ola`

SyntaxError: invalid syntax (1417184183.py, line 1)

### 1.5. Valores e Tipos

Até agora, vimos três tipos de valores:
- `2` é um inteiro,
- `42.0` é um número de ponto flutuante e
- `'Ola'` é uma string.

Um tipo de valor é chamado de **tipo**. Todo valor tem um tipo – ou às vezes dizemos que ele **pertence a** um tipo.

O Python fornece uma função chamada `type` que informa o tipo de qualquer valor. O tipo de um inteiro é `int`.

In [28]:
type(10)

int

O tipo de um número de ponto flutuante é `float`.

In [29]:
type(10.1)

float

E o tipo de uma string é `str`.

In [30]:
type('Ola, Mundo!')

str

Os tipos `int`, `float` e `str` podem ser usados ​​como funções. Por exemplo, `int` pode receber um número de ponto flutuante e convertê-lo em um inteiro (sempre arredondando para baixo).

In [31]:
int(10.3)

10

E `float` pode converter um inteiro em um valor de ponto flutuante.

In [32]:
float(10)

10.0

Agora, aqui vai algo que pode ser confuso: o que acontece se você colocar uma sequência de dígitos entre aspas?

In [33]:
'123'

'123'

Parece um número, mas na verdade é uma string.

In [34]:
type('123')

str

Se você tentar usá-lo como um número, poderá obter um erro.

In [35]:
'123' / 2

TypeError: unsupported operand type(s) for /: 'str' and 'int'

Este exemplo gera um `TypeError`, o que significa que os valores na expressão, chamados operandos, têm o tipo errado. A mensagem de erro indica que o operador `/` não suporta os tipos desses valores, que são `str` e `int`.

Se você tiver uma string que contém dígitos, você pode usar `int` para convertê-la em um inteiro.

In [36]:
int('123') / 2

61.5

Se você tiver uma string que contém dígitos e um ponto decimal, você pode usar `float` para convertê-la em um número de ponto flutuante.

In [37]:
float('10.2')

10.2

Ao escrever um número inteiro grande, você pode se sentir tentado a usar vírgulas entre grupos de dígitos, como em `1,000,000`. Esta é uma expressão válida em Python, mas o resultado não é um número inteiro.

In [38]:
1,000,000

(1, 0, 0)

O Python interpreta `1,000,000` como uma sequência de números inteiros separados por vírgulas. Falaremos mais sobre esse tipo de sequência posteriormente.

Você pode usar sublinhados para facilitar a leitura de números grandes.

In [39]:
1_000_000

1000000

### 1.6. Linguagens Natural e Formal

**Linguagens naturais** são as línguas que as pessoas falam, como português, inglês, espanhol e francês. Elas não foram projetadas por pessoas; elas evoluíram naturalmente.

**Linguagens formais** são linguagens projetadas por pessoas para aplicações específicas. Por exemplo, a notação que os matemáticos usam é uma linguagem formal que é particularmente boa para denotar relações entre números e símbolos. Da mesma forma, linguagens de programação são linguagens formais que foram projetadas para expressar cálculos.

Embora as linguagens formais e naturais tenham algumas características em comum, existem diferenças importantes:

- Ambiguidade: As linguagens naturais são cheias de ambiguidade, com a qual as pessoas lidam usando pistas contextuais e outras informações. As linguagens formais são projetadas para serem quase ou completamente inequívocas, o que significa que qualquer programa tem exatamente um significado, independentemente do contexto.

- Redundância: Para compensar a ambiguidade e reduzir mal-entendidos, as linguagens naturais usam redundância. Como resultado, elas costumam ser prolixas. As linguagens formais são menos redundantes e mais concisas.

- Literalidade: As linguagens naturais são cheias de expressões idiomáticas e metáforas. Linguagens formais significam exatamente o que dizem.

Como todos crescemos falando linguagens naturais, às vezes é difícil nos adaptarmos às linguagens formais. As linguagens formais são mais densas do que as linguagens naturais, por isso levam mais tempo para serem lidas. Além disso, a estrutura é importante, por isso nem sempre é melhor ler de cima para baixo, da esquerda para a direita. Por fim, os detalhes importam. Pequenos erros de ortografia e pontuação, que você pode evitar em linguagens naturais, podem fazer uma grande diferença em uma linguagem formal.

### 1.7. Depuração (*Debugging*)

Programadores cometem erros. Por motivos excêntricos, erros de programação são chamados de **bugs** e o processo de rastreá-los é chamado de depuração (**debugging**).

Programar, e especialmente depurar, às vezes desperta emoções fortes. Se você está lutando contra um bug difícil, pode se sentir irritado, triste ou envergonhado.

Preparar-se para essas reações pode ajudá-lo a lidar com elas. Uma abordagem é pensar no computador como um funcionário com certos pontos fortes, como velocidade e precisão, e fraquezas específicas, como falta de empatia e incapacidade de compreender o panorama geral.

Seu trabalho é ser um bom gerente: encontre maneiras de aproveitar os pontos fortes e mitigar os pontos fracos. E encontre maneiras de usar suas emoções para se envolver com o problema, sem deixar que suas reações interfiram em sua capacidade de trabalhar com eficácia.

Aprender a depurar pode ser frustrante, mas é uma habilidade valiosa e útil para muitas atividades além da programação.

### 1.8. Exercícios

In [40]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose


#### 1.8.1. Exercício

Ao aprender sobre um novo recurso, você deve experimentá-lo e cometer erros de propósito. Dessa forma, você aprende as mensagens de erro e, quando as vir novamente, saberá o que significam. É melhor cometer erros agora e deliberadamente do que mais tarde e acidentalmente.

1. Você pode usar um sinal de menos para formar um número negativo como `-2`. O que acontece se você colocar um sinal de mais antes de um número? E quanto a `2++2`?

In [42]:
+2

2

In [ ]:
2++2

4

In [45]:
2++ +2

4

2. O que acontece se você tiver dois valores sem operador entre eles, como `4 2`?

In [46]:
4 2

SyntaxError: invalid syntax (436257307.py, line 1)

3. Se você chamar uma função como `round(42.5)`, o que acontece se você omitir um ou ambos os parênteses?

In [47]:
round(42.5)

42

In [48]:
round42.5)

SyntaxError: unmatched ')' (887526850.py, line 1)

In [49]:
round 42.5

SyntaxError: invalid syntax (2283105285.py, line 1)

#### 1.8.2. Exercício

Lembre-se de que toda expressão tem um valor, todo valor tem um tipo, e podemos usar a função `type` para encontrar o tipo de qualquer valor.

Qual é o tipo do valor das seguintes expressões? Faça sua melhor estimativa para cada uma delas e, em seguida, use type para descobrir.

- `765` - int
- `2.718` - float
- `'2 pi'` - str
- `abs(-7)` - int
- `abs(-7.0)` - float
- `abs` - function
- `int` - type
- `type` - type

In [50]:
type(765)

int

In [51]:
type(2.718)

float

In [52]:
type('2 pi')

str

In [53]:
type( abs(-7) )

int

In [54]:
type( abs(-7.0) )

float

In [55]:
type(abs)

builtin_function_or_method

In [56]:
type(int)

type

In [57]:
type(type)

type

## 2. Variáveis e Comandos

Na seção anterior, usamos operadores para escrever expressões que realizam cálculos aritméticos.

Nesta seção, vamos abordar variáveis ​​e comandos do Python, a instrução `import` e a função `print`. Além disso, será introduzido o conceito de "argumento" e "módulo", que usamos para falar sobre programas.

### 2.1. Variáveis

Uma **variável** é um nome que se refere a um valor. Para criar uma variável, podemos escrever uma instrução de atribuição como esta.

In [58]:
n = 10

Uma instrução de atribuição tem três partes: o nome da variável à esquerda, o operador de igualdade, `=`, e uma expressão à direita. Neste exemplo, a expressão é um inteiro. No exemplo a seguir, a expressão é um número de ponto flutuante.

In [59]:
pi = 3.141592653589793

E no exemplo a seguir, a expressão é uma string.

In [60]:
mensagem = 'E agora algo completamente diferente'

Ao executar uma instrução de atribuição, não há saída. O Python cria a variável e atribui um valor a ela, mas a instrução de atribuição não tem efeito visível. No entanto, após criar uma variável, você pode usá-la como uma expressão. Assim, podemos exibir o valor de `mensagem` assim:

In [61]:
mensagem

'E agora algo completamente diferente'

Você também pode usar uma variável como parte de uma expressão com operadores aritméticos.


In [62]:
n + 25

35

In [63]:
2 * pi

6.283185307179586

E você pode usar uma variável quando chamar uma função.

In [64]:
round(pi)

3

In [65]:
len(mensagem)

36

### 2.2. Diagrama de Estado

Uma maneira comum de representar variáveis ​​no papel é escrever o nome com uma seta apontando para o seu valor.

![Diagrama de Estado](./img/2_2_state_diagram.png)

Esse tipo de figura é chamado de **diagrama de estado** porque mostra em que estado cada variável se encontra (pense nisso como o estado interno da variável). Usaremos diagramas de estado para representar um modelo de como o Python armazena variáveis ​​e seus valores.

### 2.3. Nome de Variáveis

Os nomes de variáveis ​​podem ser tão longos quanto você quiser. Eles podem conter letras e números, mas não podem começar com um número. É permitido usar letras maiúsculas, mas é convencional usar apenas letras minúsculas para nomes de variáveis.

A única pontuação que pode aparecer em um nome de variável é o caractere de sublinhado, `_`. Ele é frequentemente usado em nomes com várias palavras, como `seu_nome` ou `velocidade_do_ar_de_andorinha_sem_carga`.

Se você atribuir um nome ilegal a uma variável, receberá um erro de sintaxe. O nome `million!` é ilegal porque contém pontuação.

In [66]:
million! = 1000000

SyntaxError: invalid syntax (347180775.py, line 1)

`76trombones` é ilegal porque começa com um número.

In [67]:
76trombones = 'grande desfile'

SyntaxError: invalid decimal literal (1800748638.py, line 1)

`class` também é ilegal, mas pode não ser óbvio o porquê.

In [68]:
class = 'Autodefesa contra frutas frescas'

SyntaxError: invalid syntax (3342871884.py, line 1)

Acontece que `class` é uma palavra-chave, que é uma palavra especial usada para especificar a estrutura de um programa. Palavras-chave não podem ser usadas como nomes de variáveis.

Aqui está uma lista completa de palavras-chave do Python:
```
False      await      else       import     pass
None       break      except     in         raise
True       class      finally    is         return
and        continue   for        lambda     try
as         def        from       nonlocal   while
assert     del        global     not        with
async      elif       if         or         yield
```

Você não precisa memorizar esta lista. Na maioria dos ambientes de desenvolvimento, as palavras-chave são exibidas em uma cor diferente; se você tentar usar uma como nome de variável, saberá.

### 2.4. O Comando import

Para usar alguns recursos do Python, você precisa importá-los. Por exemplo, a instrução a seguir importa o módulo `math` para valores e operações matemáticas importantes.

In [69]:
import math

Um módulo é uma coleção de variáveis ​​e funções. O módulo `math` fornece uma variável chamada `pi` que contém o valor da constante matemática denotada por $\pi$. Podemos exibir seu valor assim.

In [70]:
math.pi

3.141592653589793

Para usar uma variável de um módulo, você precisa usar o operador ponto (`.`) entre o nome do módulo e o nome da variável.

O módulo `math` também contém funções. Por exemplo, `sqrt` calcula raízes quadradas.

In [71]:
math.sqrt(16)

4.0

E `pow` eleva um número à potência de um segundo número.

In [72]:
math.pow(2, 4)

16.0

Até aqui, vimos duas maneiras de elevar um número a uma potência: podemos usar a função `math.pow` ou o operador de exponenciação, `**`. Qualquer uma delas funciona, mas o operador é usado com mais frequência do que a função.

### 2.5. Expressões e Comandos

Até agora, vimos alguns tipos de expressões. Uma expressão pode ser um único valor, como um inteiro, um número de ponto flutuante ou uma string. Também pode ser uma coleção de valores e operadores. E pode incluir nomes de variáveis ​​e chamadas de função. Aqui está uma expressão que inclui vários desses elementos.

In [73]:
19 + n + round(math.pi) * 2

35

Também vimos alguns tipos de instruções. Um `comando` é uma unidade de código que tem um efeito, mas nenhum valor. Por exemplo, uma instrução de atribuição cria uma variável e atribui um valor a ela, mas o comando em si não tem valor.

In [74]:
n = 17

Da mesma forma, o ccomando `import` tem um efeito – ela importa um módulo para que possamos usar as variáveis ​​e funções que ele contém – mas não tem efeito visível.

In [75]:
import math

Calcular o valor de uma expressão é chamado de **avaliação**. Executar um comando é chamado de **execução**.

### 2.6. A Função print

Quando você avalia uma expressão, o resultado é exibido.

In [76]:
n + 1

18

Mas se você avaliar mais de uma expressão, somente o valor da última será exibido.

In [77]:
n + 2
n + 3

20

Para exibir mais de um valor, você pode usar a função `print`.

In [78]:
print(n + 2)
print(n + 3)

19
20


Ele também funciona com números de ponto flutuante e strings.

In [79]:
print('O valor de pi é aproximadamente')
print(math.pi)

O valor de pi é aproximadamente
3.141592653589793


Você também pode usar uma sequência de expressões separadas por vírgulas.

In [80]:
print('O valor de pi é aproximadamente', math.pi)

O valor de pi é aproximadamente 3.141592653589793


Observe que a função `print` coloca um espaço entre os valores.

### 2.7. Argumentos

Quando você chama uma função, a expressão entre parênteses é chamada de `argumento`. Algumas das funções que vimos até agora aceitam apenas um argumento, como `int`.

In [81]:
int('101')

101

Alguns usam dois, como o `math.pow`.

In [82]:
math.pow(2, 4)

16.0

Algumas podem receber argumentos adicionais opcionais. Por exemplo, `int` pode receber um segundo argumento que especifica a base do número.

In [83]:
int('101', 2)

5

A sequência de dígitos `101` na base 2 representa o número 5 na base 10.

`round` também aceita um segundo argumento opcional, que é o número de casas decimais para arredondar.

In [84]:
round(math.pi, 4)

3.1416

Algumas funções podem receber qualquer número de argumentos, como `print`.

In [85]:
print('Qualquer', 'número', 'de', 'argumentos')

Qualquer número de argumentos


Se você chamar uma função e fornecer muitos argumentos, isso é um `TypeError`.

In [86]:
float('101.0', 2)

TypeError: float expected at most 1 argument, got 2

Se você fornecer poucos argumentos, isso também será um `TypeError`.

In [87]:
math.pow(2)

TypeError: pow expected 2 arguments, got 1

E se você fornecer um argumento com um tipo que a função não pode manipular, isso também é um `TypeError`.

In [88]:
math.sqrt('81')

TypeError: must be real number, not str

Esse tipo de verificação pode ser irritante quando você está começando, mas ajuda a detectar e corrigir erros.

### 2.8. Comentários

À medida que os programas se tornam maiores e mais complexos, tornam-se mais difíceis de ler. Linguagens formais são densas e, muitas vezes, é difícil analisar um trecho de código e descobrir o que ele está fazendo e por quê.

Por esse motivo, é uma boa ideia adicionar notas aos seus programas para explicar em linguagem natural o que o programa está fazendo. Essas notas são chamadas de **comentários** e começam com o símbolo `#`.

In [90]:
# número de segundos em 42:42
segundos = 42 * 60 + 42

Neste caso, o comentário aparece sozinho em uma linha. Você também pode colocar comentários no final de uma linha:

In [91]:
milhas = 10 / 1.61 # 10 quilômetros em milhas

Tudo, desde o `#` até o final da linha, é ignorado — não afeta a execução do programa.

Comentários são mais úteis quando documentam características não óbvias do código. É razoável supor que o leitor consiga descobrir *o que* o código faz; é mais útil explicar *o porquê*.

Este comentário é redundante com o código e inútil:

In [92]:
v = 8 # atribui 8 a v

Este comentário contém informações úteis que não estão no código:

In [93]:
v = 8 # velocidade em milhas por hora

Bons nomes de variáveis ​​podem reduzir a necessidade de comentários, mas nomes longos podem tornar expressões complexas difíceis de ler, então há uma compensação.

### 2.9. Exercícios

In [94]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose


#### 2.9.1 Exercício

Mais uma vez, sempre que aprender um novo recurso, cometa erros de propósito para ver o que dá errado.

- Vimos que `n = 17` é válido. E quanto a `17 = n`?

- E quanto a `x = y = 1`?

- Em algumas linguagens, todo comando termina com ponto e vírgula (`;`). O que acontece se você colocar um ponto e vírgula no final de uma instrução Python?

- E se você colocar um ponto final no final de um comando?

- O que acontece se você digitar o nome de um módulo errado e tentar importar o `maath`?

In [95]:
17 = n

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (1575534540.py, line 1)

In [97]:
x = y = 1
print(x)
print(y)

1
1


In [98]:
n = 17;

In [100]:
a = '18'.

SyntaxError: invalid syntax (3799121788.py, line 1)

In [101]:
import maath

ModuleNotFoundError: No module named 'maath'

#### 2.9.2 Exercício

Pratique o uso do interpretador Python como calculadora:

**Parte 1**. O volume de uma esfera com raio é $\frac{4}{3} \pi r^3$. Qual é o volume de uma esfera com raio 5? Comece com uma variável chamada `raio` e, em seguida, atribua o resultado a uma variável chamada `volume`. Exiba o resultado. Adicione comentários para indicar que o raio está em centímetros e o volume em centímetros cúbicos.

In [108]:
raio = 5 # raio de uma esfera em centímetros
volume = (4 / 3) * math.pi * raio**3 # volume de uma esfera em centímetros cúbicos
volume

523.5987755982989

**Parte 2**. Uma regra da trigonometria diz que para qualquer valor de $x$, $(\cos x)^2 + (\sin x)^2 = 1$. Vamos ver se isso é verdade para um valor específico de $x$ como 42.

Crie uma variável chamada `x` com esse valor. Em seguida, use `math.cos` e `math.sin` para calcular o seno e o cosseno de
$x$, e a soma de seus quadrados.

O resultado deve ser próximo de 1. Pode não ser exatamente 1 porque a aritmética de ponto flutuante não é exata — ela é apenas aproximadamente correta.

In [109]:
x = 42
cos = math.cos(x)
sin = math.sin(x)
print(cos**2 + sin**2)

1.0


**Parte 3**. Além de `pi`, a outra variável definida no módulo `math` é `e`, que representa a base do logaritmo natural, escrito em notação matemática como $e$. Agora vamos calcular $e^2$ de três maneiras:

- Use `math.e` e o operador de exponenciação (`**`).

- Use `math.pow` para elevar `math.e` à potência `2`.

- Use `math.exp`, que recebe como argumento um valor, $x$, e calcula $e^x$.

Você pode notar que o último resultado é ligeiramente diferente dos outros dois. Veja se consegue descobrir qual está correto.

In [110]:
print(math.e ** 2)
print(math.pow(math.e, 2))
print(math.exp(2))

7.3890560989306495
7.3890560989306495
7.38905609893065


## 3. Funções

Na seção anterior, usamos várias funções fornecidas pelo Python, como `int` e `float`, e algumas fornecidas pelo módulo `math`, como `sqrt` e `pow`. Nesta seção, você aprenderá a criar suas próprias funções e executá-las. E veremos como uma função pode chamar outra. Como exemplos, exibiremos letras de músicas do [Monty Python](https://en.wikipedia.org/wiki/Monty_Python). Esses exemplos simples demonstram um recurso importante: a capacidade de escrever suas próprias funções como a base da programação.

### 3.1. Definindo Novas Funções

Uma **definição de função** especifica o nome de uma nova função e a sequência de instruções/comandos que são executadas quando a função é chamada. Veja um exemplo:

In [112]:
def print_lyrics():
    print("I'm a lumberjack, and I'm okay.")
    print("I sleep all night and I work all day.")

`def` é uma palavra-chave que indica que esta é uma definição de função. O nome da função é `print_lyrics`. Qualquer nome de variável válido também é um nome de função válido.

Os parênteses vazios após o nome indicam que esta função não aceita argumentos.

A primeira linha da definição da função é chamada de **cabeçalho** – o restante é chamado de **corpo**. O cabeçalho deve terminar com dois pontos e o corpo deve ser recuado. Por convenção, o recuo é sempre de **quatro espaços** (um **tab**). O corpo desta função consiste em duas instruções `print`; em geral, o corpo de uma função pode conter qualquer número de instruções de qualquer tipo.

Definir uma função cria um objeto de função, que podemos exibir assim.

In [113]:
print_lyrics

<function __main__.print_lyrics()>

A saída indica que `print_lyrics` é uma função que não aceita argumentos. `__main__` é o nome do módulo que contém `print_lyrics`.

Agora que definimos uma função, podemos chamá-la da mesma forma que chamamos funções internas.

In [114]:
print_lyrics()

I'm a lumberjack, and I'm okay.
I sleep all night and I work all day.


Quando a função é executada, ela executa as instruções no corpo, que exibem as duas primeiras linhas de ["The Lumberjack Song"](https://www.songfacts.com/facts/monty-python/the-lumberjack-song).

### 3.2. Parâmetros

Algumas das funções que vimos exigem argumentos; por exemplo, ao chamar `abs`, você passa um número como argumento. Algumas funções aceitam mais de um argumento; por exemplo, `math.pow` aceita dois, a base e o expoente.

Aqui está uma definição para uma função que aceita um argumento.

In [115]:
def print_twice(string):
    print(string)
    print(string)

O nome da variável entre parênteses é um **parâmetro**. Quando a função é chamada, o valor do argumento é atribuído ao parâmetro. Por exemplo, podemos chamar `print_twice` assim.

In [116]:
print_twice('Dennis Moore, ')

Dennis Moore, 
Dennis Moore, 


Executar esta função tem o mesmo efeito que atribuir o argumento ao parâmetro e então executar o corpo da função, assim.

In [117]:
string = 'Dennis Moore, '
print(string)
print(string)

Dennis Moore, 
Dennis Moore, 


Você também pode usar uma variável como argumento.

In [118]:
linha = 'Dennis Moore, '
print_twice(linha)

Dennis Moore, 
Dennis Moore, 


Neste exemplo, o valor da `linha` é atribuído ao parâmetro `string`.

### 3.3. Chamando Funções

Depois de definir uma função, você pode usá-la dentro de outra função. Para demonstrar, escreveremos funções que imprimem a letra de ["The Spam Song"](https://www.songfacts.com/lyrics/monty-python/the-spam-song).

> Spam, Spam, Spam, Spam,  
> Spam, Spam, Spam, Spam,  
> Spam, Spam,  
> (Lovely Spam, Wonderful Spam!)  
> Spam, Spam,

Começaremos com a seguinte função, que recebe dois parâmetros.

In [119]:
def repete(palavra, n):
    print(palavra * n)

Podemos usar esta função para imprimir a primeira linha da música, assim.

In [120]:
spam = 'Spam, '
repete(spam, 4)

Spam, Spam, Spam, Spam, 


Para exibir as duas primeiras linhas, podemos definir uma nova função que usa `repete`.

In [121]:
def duas_primeiras_linhas():
    repete(spam, 4)
    repete(spam, 4)

E então chame assim.

In [122]:
duas_primeiras_linhas()

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 


Para exibir as últimas três linhas, podemos definir outra função, que também usa `repete`.

In [123]:
def ultimas_tres_linhas():
    repete(spam, 2)
    print('(Lovely Spam, Wonderful Spam!)')
    repete(spam, 2)

In [124]:
ultimas_tres_linhas()

Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 


Por fim, podemos reunir tudo com uma função que imprime o verso inteiro.

In [125]:
def print_verso():
    duas_primeiras_linhas()
    ultimas_tres_linhas()

In [126]:
print_verso()

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 


Quando executamos `print_verso`, ele chama `duas_primeiras_linhas`, que chama `repete`, que chama `print`. São muitas funções.

Claro, poderíamos ter feito a mesma coisa com menos funções, mas o objetivo deste exemplo é mostrar como funções podem funcionar juntas.

### 3.4. Retorno de Funções

Quando você chama uma função como `math.sqrt`, o resultado é chamado de **valor de retorno**. Se a chamada da função aparecer no final de uma célula, o Jupyter exibe o valor de retorno imediatamente.

In [127]:
import math

math.sqrt(42 / math.pi)

3.656366395715726

Se você atribuir o valor de retorno a uma variável, ele não será exibido.

In [128]:
raio = math.sqrt(42 / math.pi)


In [129]:
raio

3.656366395715726

Ou você pode usar o valor de retorno como parte de uma expressão.

In [130]:
raio + math.sqrt(42 / math.pi)


7.312732791431452

Aqui está um exemplo de uma função que retorna um valor.

In [131]:
def circulo_area(raio):
    area = math.pi * raio**2
    return area

`circulo_area` recebe `raio` como parâmetro e calcula a área de um círculo com esse raio.

A última linha é uma instrução `return` que retorna o valor de area.

Se chamarmos a função dessa forma, o Jupyter exibirá o valor de retorno.

In [132]:
circulo_area(raio)

42.00000000000001

Podemos atribuir o valor de retorno a uma variável.

In [133]:
a = circulo_area(raio)

Ou use-a como parte de uma expressão.

In [134]:
circulo_area(raio) + 2 * circulo_area(raio/2)

63.000000000000014

Mais tarde, podemos exibir o valor da variável à qual atribuímos o resultado.

In [135]:
a

42.00000000000001

Se uma função não tiver uma instrução `return`, ela retornará `None`, que é um valor especial como `True` e `False`. Por exemplo, veja a função `repete`.

In [136]:
def repete(palavra, n):
    print(palavra * n)

Se chamarmos assim, ela exibe o primeiro verso da música ["Filand"](https://genius.com/Monty-python-finland-song-monty-python-sings-lyrics) do Monty Python.

In [137]:
resultado = repete('Finland, ', 3)

Finland, Finland, Finland, 


E se exibirmos o valor da variável, não obteremos nada.

In [138]:
resultado

`resultado` na verdade tem um valor, mas o Jupyter não o mostra. No entanto, podemos exibi-lo assim.

In [139]:
print(resultado)

None


O valor de retorno de `repete` é `None`.

Aqui está uma função semelhante a `repete`, exceto que tem um valor de retorno.

In [140]:
def repete_string(palavra, n):
    return palavra * n

Observe que podemos usar uma expressão em uma instrução `return`, não apenas uma variável.

Com esta versão, podemos atribuir o resultado a uma variável. Quando a função é executada, ela não exibe nada.

In [141]:
linha = repete_string('Spam, ', 4)

Mas depois podemos exibir o valor atribuído à `linha`.

In [142]:
linha

'Spam, Spam, Spam, Spam, '

Uma função como essa é chamada de **função pura** porque não exibe nada nem tem qualquer outro efeito, além de retornar um valor.

### 3.5. Repetição (`for` e `while`)

Se quisermos exibir mais de um verso, podemos usar a instrução `for`. 

```python
for variavel in minha_string_ou_lista :
  # faça alguma coisa com variavel
```

A `variavel` que aparece logo após a palavra `for` vai receber o valor de cada elemento da `minha_string_ou_lista` por vez.

Aqui está um exemplo simples.

In [143]:
for i in range(2):
    print(i)

0
1


A primeira linha é um cabeçalho que termina com dois pontos. A segunda linha é o corpo, que precisa ser recuado.

O cabeçalho começa com a palavra-chave `for`, uma nova variável chamada `i` e outra palavra-chave, `in`. Ele usa a função `range` para criar uma sequência de dois valores, que são `0` e `1`. Em Python, quando começamos a contar, geralmente começamos do `0`.

Quando o comando `for` é executado, ele atribui o primeiro valor de `range` a `i` e, em seguida, executa a função `print` no corpo, que exibe `0`.

Quando chega ao final do corpo, ela retorna ao cabeçalho, e é por isso que esse comando é chamado de **laço (loop)**. Na segunda vez que passa pelo loop, ela atribui o próximo valor de `range` a `i` e o exibe. Então, como esse é o último valor de `range`, o loop termina.

Veja como podemos usar um loop `for` para imprimir dois versos da música.

In [144]:
for i in range(2):
    print("Verso", i)
    print_verso()
    print()

Verso 0
Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 

Verso 1
Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 



Você pode colocar um loop for dentro de uma função. Por exemplo, `print_n_versos` recebe um parâmetro chamado `n`, que deve ser um inteiro, e exibe o número de versos fornecido.

In [145]:
def print_n_versos(n):
    for i in range(n):
        print_verso()
        print()

print_n_versos(4)

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 

Spam, Spam, Spam, Spam, 
Spam, Spam, Spam, Spam, 
Spam, Spam, 
(Lovely Spam, Wonderful Spam!)
Spam, Spam, 



Neste exemplo, não usamos `i` no corpo do loop, mas de qualquer forma, tem que haver um nome de variável no cabeçalho.

O comando `while` (que significa enquanto) é outro tipo de estrutura de repetição em Python.

Ele é muito útil quando precisamos repetir um trecho de código.

O `while` é parecido com um comando `if`: ele vai executar o código dentro dele se determinada condição for verdadeira. A diferença é que o comando `while` continuará executando **enquanto** aquela condição for verdadeira.

Normalmente ele tem a seguinte sintaxe:
```python
while condicao :
  comandos
```  

Estruturas de repetição são também chamadas de **laço** ou **loop**.

Exemplo de uso do comando `while`:

In [146]:
cont = 0
while cont < 5:
  print("Olá, eu sou um laço while e cont é", cont)
  cont = cont + 1

Olá, eu sou um laço while e cont é 0
Olá, eu sou um laço while e cont é 1
Olá, eu sou um laço while e cont é 2
Olá, eu sou um laço while e cont é 3
Olá, eu sou um laço while e cont é 4


No exemplo acima, a linha 2 decide quando o loop será executado. Portanto, *enquanto cont for menor do 5*, o loop vai continuar a executar. A linha 4 aumenta cont em 1, isso acontece repetidamente até que cont seja igual a 5.

### 3.6. Variáveis ​​e Parâmetros são Locais

Quando você cria uma variável dentro de uma função, ela é **local**, o que significa que ela só existe dentro da função. Por exemplo, a função a seguir recebe dois argumentos, concatena-os e imprime o resultado duas vezes.

In [147]:
def cat_twice(part1, part2):
    cat = part1 + part2
    print_twice(cat)

Aqui está um exemplo que o utiliza:

In [148]:
linha1 = 'Always look on the '
linha2 = 'bright side of life.'
cat_twice(linha1, linha2)

Always look on the bright side of life.
Always look on the bright side of life.


Quando `cat_twice` é executado, ele cria uma variável local chamada `cat`, que é destruída quando a função termina. Se tentarmos exibi-la, obteremos um `NameError`:

In [149]:
print(cat)

NameError: name 'cat' is not defined

Fora da função, `cat` não é definido.

Os parâmetros também são locais. Por exemplo, fora de `cat_twice`, não existe `part1` ou `part2`.

### 3.7. Rastreamentos (Tracebacks)

Quando ocorre um erro de execução em uma função, o Python exibe o nome da função que estava em execução, o nome da função que a chamou e assim por diante, na pilha. Para ver um exemplo, definirei uma versão de `print_twice` que contém um erro – ela tenta imprimir `cat`, que é uma variável local em outra função.

In [150]:
def print_twice(string):
    print(cat)            # NameError
    print(cat)

Agora, aqui está o que acontece quando executamos `cat_twice`.

In [151]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorre um erro de tempo de execução, incluindo um traceback.

%xmode Verbose

Exception reporting mode: Verbose


In [152]:
cat_twice(linha1, linha2)

NameError: name 'cat' is not defined

A mensagem de erro inclui um **traceback**, que mostra a função que estava em execução quando o erro ocorreu, a função que a chamou e assim por diante. Neste exemplo, ele mostra que `cat_twice` chamou `print_twice` e o erro ocorreu em um `print_twice`.

### 3.8. Docstrings

Uma **docstring** é uma string no início de uma função que explica a interface ("doc" é a abreviação de "documentação"). Aqui está um exemplo:

In [153]:
def cat_twice(part1, part2):
    """Concatena os dois argumentos (as partes) e imprime duas vezes o resultado da concatenação.
    
    part1: é uma string da primeira parte
    part2: é uma string da segunda parte
    """
    cat = part1 + part2
    print_twice(cat)

Por convenção, docstrings são strings entre aspas triplas, também conhecidas como **strings multilinhas**, pois as aspas triplas permitem que a string ocupe mais de uma linha.

Uma docstring deve:

- Explicar concisamente o que a função faz, sem entrar em detalhes sobre seu funcionamento,

- Explicar o efeito de cada parâmetro no comportamento da função e

- Indicar o tipo de cada parâmetro, caso não seja óbvio.

Escrever esse tipo de documentação é uma parte importante do design de interfaces de funções. Uma interface bem projetada deve ser simples de explicar; se você tiver dificuldade em explicar uma de suas funções, talvez a interface possa ser melhorada.

### 3.9. Por que Funções?

Talvez ainda não esteja claro por que vale a pena dividir um programa em funções. Há vários motivos:

- Criar uma nova função oferece a oportunidade de nomear um grupo de instruções, o que torna seu programa mais fácil de ler e depurar.

- As funções podem tornar um programa menor, eliminando código repetitivo. Posteriormente, se você fizer uma alteração, precisará fazê-la apenas em um lugar.

- Dividir um programa longo em funções permite depurar as partes uma de cada vez e, em seguida, reuni-las em um todo funcional.

- Funções bem projetadas costumam ser úteis para muitos programas. Depois de escrever e depurar uma, você pode reutilizá-la.

### 3.10. Exercícios

In [154]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose


#### 3.10.1 Exercício

Escreva uma função chamada `print_right` que receba uma string chamada `text` como parâmetro e imprima a string com espaços à esquerda suficientes para que a última letra da string fique na 40ª coluna da tela.

Dica: Use a função `len`, o operador de concatenação de strings (`+`) e o operador de repetição de strings (`*`).

Aqui está um exemplo que mostra como isso deve funcionar.

~~~python
print_right("Monty")
print_right("Python's")
print_right("Flying Circus")
~~~

```
                                   Monty
                                Python's
                           Flying Circus
```

In [157]:
def print_right(text: str) -> None:
    """Recebe uma string text como parâmetro e imprime a string com espaços à esquerda de modo que
    a última letra da string esteja na 40ª coluna da tela
    
    text: texto a ser exibido
    """
    vazios = 40 - len(text)
    print(' ' * vazios + text)

print_right('Monty')
print_right("Python's")
print_right('Flying Circus')

                                   Monty
                                Python's
                           Flying Circus


#### 2.10.2 Exercício

Escreva uma função chamada `triangulo` que recebe uma string e um inteiro e desenha uma pirâmide com a altura fornecida, construída com cópias da string. Aqui está um exemplo de uma pirâmide com `5` níveis, usando a string `'L'`.

~~~python
triangulo('L', 5)
~~~

```
L
LL
LLL
LLLL
LLLLL
```

In [160]:
def triangulo(text: str, altura: int) -> None:
    """Desenha uma pirâmide com a altura fornecida a partir das cópias do texto fornecido

    text: texto fornecido para formar a pirâmide
    altura: altura da pirâmide
    """
    for i in range(altura + 1):
        print(text * i)

triangulo('U', 7)


U
UU
UUU
UUUU
UUUUU
UUUUUU
UUUUUUU


#### 2.10.3. Exercício

Escreva uma função chamada `retangulo` que recebe uma string e dois inteiros e desenha um retângulo com a largura e altura fornecidas, criado a partir de cópias da string. Aqui está um exemplo de um retângulo com largura `5` e altura `4`, composto pela string `'H'`.

~~~python
retangulo('H', 5, 4)
~~~

```
HHHHH
HHHHH
HHHHH
HHHHH
```

In [161]:
def retangulo(text: str, largura: int, altura: int) -> None:
    """Desenha um retângulo com a altura e largura fornecidas a partir das cópias do texto fornecido
    
    text: texto fornecido para formar o retângulo
    largura: largura do retângulo
    altura: altura do retângulo
    """
    cont = 0
    while cont < altura:
        print(text * largura)
        cont = cont + 1

retangulo('H', 5, 4)

HHHHH
HHHHH
HHHHH
HHHHH


## 4. Condicionais e Recursão

O tópico principal desta seção é o comando `if`, que executa códigos diferentes dependendo do estado do programa. E com ele, poderemos explorar uma das ideias mais poderosas da computação: a recursão.

Mas começaremos com três novos recursos: o operador de módulo, expressões booleanas e operadores lógicos.

### 4.1. Divisão Inteira e Módulo

Lembre-se de que o operador de divisão de inteiros, `//`, divide dois números e arredonda para baixo, resultando em um número inteiro. Por exemplo, suponha que a duração de um filme seja de `105` minutos. Você pode querer saber quanto tempo isso dura em horas. A divisão convencional retorna um número de ponto flutuante:

In [162]:
minutos = 105
minutos / 60

1.75

Mas normalmente não escrevemos horas com pontos decimais. A divisão inteira retorna o número inteiro de horas, arredondado para baixo:

In [163]:
minutos = 105
horas = minutos // 60
horas

1

Para obter o restante, você pode subtrair uma hora em minutos:

In [164]:
resto = minutos - horas * 60
resto

45

Ou você pode usar o operador de módulo, `%`, que divide dois números e retorna o resto.

In [165]:
resto = minutos % 60
resto

45

O operador de módulo é mais útil do que parece. Por exemplo, ele pode verificar se um número é divisível por outro – se `x % y` for zero, então `x` é divisível por `y`.

Além disso, ele pode extrair o(s) dígito(s) mais à direita de um número. Por exemplo, `x % 10` produz o dígito mais à direita de `x` (na base 10). Da mesma forma, `x` % 100 produz os dois últimos dígitos.

In [166]:
x = 123
x % 10

3

In [167]:
x % 100

23

Por fim, o operador de módulo pode fazer "aritmética de relógio". Por exemplo, se um evento começa às 11h e dura três horas, podemos usar o operador de módulo para descobrir a que horas ele termina.

In [168]:
início = 11
duração = 3
fim = (início + duração) % 12
fim

2

O evento terminaria às 14h.

### 4.2. Expressões Booleanas

Uma expressão booleana é uma expressão que pode ser verdadeira ou falsa. Por exemplo, as seguintes expressões usam o operador de igualdade, `==`, que compara dois valores e produz `True` se forem iguais e `False` caso contrário:

In [169]:
5 == 5

True

In [170]:
5 == 7

False

Um erro comum é usar um único sinal de igual (`=`) em vez de dois sinais de igual (`==`). Lembre-se de que `=` atribui um valor a uma variável e `==` compara dois valores.

In [171]:
x = 5
y = 7

In [172]:
x == y

False

`True` e `False` são valores especiais que pertencem ao tipo `bool`; eles não são strings:

In [173]:
type(True)

bool

In [174]:
type(False)

bool

O operador == é um dos **operadores relacionais**; os outros são:

In [175]:
x != y # x não é igual a y

True

In [176]:
x > y # x é maior que y

False

In [177]:
x < y # x é menor que y

True

In [178]:
x >= y # x é maior ou igual a y

False

In [179]:
x <= y # x é menor ou igual a y

True

### 4.3. Operadores Lógicos

Para combinar valores booleanos em expressões, podemos usar operadores lógicos. Os mais comuns são `and`, `or` e `not`. O significado desses operadores é semelhante ao seu significado em inglês. Por exemplo, o valor da seguinte expressão é `True` somente se `x` for maior que `0` e menor que `10`.

In [180]:
x > 0 and x < 10

True

A expressão a seguir é `True` se *uma ou ambas as condições* forem verdadeiras, ou seja, se o número for divisível por `2` *ou* `3`:

In [181]:
x % 2 == 0 or x % 3 == 0


False

Por fim, o operador `not` nega uma expressão booleana, então a expressão a seguir é `True` se `x > y` for `False`.

In [182]:
not x > y

True

A rigor, as operações de um operador lógico devem ser expressões booleanas, mas Python não é muito rigoroso. Qualquer número diferente de zero é interpretado como `True`:

In [183]:
42 and True

True

Essa flexibilidade pode ser útil, mas há algumas sutilezas que podem ser confusas. Talvez seja melhor evitá-la.

### 4.4. O Comando if

Para escrever programas úteis, quase sempre precisamos da capacidade de verificar condições e alterar o comportamento do programa de acordo. **Instruções condicionais** nos dão essa capacidade. A forma mais simples é a instrução `if`:

In [184]:
if x > 0:
    print('x é positivo')

x é positivo


`if` é uma palavra-chave do Python. Instruções `if` têm a mesma estrutura que definições de função: um cabeçalho seguido por uma instrução ou sequência de instruções recuada, chamada de `bloco`.

A expressão booleana após `if` é chamada de **condição**. Se for verdadeira, as instruções no bloco recuado são executadas. Caso contrário, não são executadas.

Não há limite para o número de instruções que podem aparecer no bloco, mas deve haver pelo menos uma. Ocasionalmente, é útil ter um bloco que não faça nada – geralmente como um espaço reservado para código que você ainda não escreveu. Nesse caso, você pode usar a instrução `pass`, que não faz nada.

In [185]:
if x < 0:
    pass          # TODO: precisa lidar com valores negativos!


A palavra `TODO` em um comentário é um lembrete convencional de que há algo que você precisa fazer mais tarde.

### 4.5. A cláusula else

Uma instrução `if` pode ter uma segunda parte, chamada cláusula `else`. A sintaxe é semelhante a esta:

In [186]:
if x % 2 == 0:
    print('x é par')
else:
    print('x é ímpar')

x é ímpar


Se a condição for verdadeira, a primeira instrução recuada é executada; caso contrário, a segunda instrução recuada é executada.

Neste exemplo, se `x` for par, o resto da divisão de `x` por `2` será `0`, então a condição é verdadeira e o programa exibe que `x é par`. Se `x` for ímpar, o resto será `1`, então a condição é falsa e o programa exibe que `x é ímpar`.

Como a condição deve ser verdadeira ou falsa, exatamente uma das alternativas será executada. As alternativas são chamadas de **desvios** (desvios condicionais ou *braches*).

### 4.6. Condicionais Encadeados

Às vezes, há mais de duas possibilidades e precisamos de mais de dois desvios/ramos. Uma maneira de expressar um cálculo como esse é uma condicional encadeada, que inclui uma cláusula `elif`.

In [187]:
if x < y:
    print('x é menor que y')
elif x > y:
    print('x é maior que y')
else:
    print('x e y são iguais')

x é menor que y


`elif` é uma abreviação de "else if". Não há limite para o número de cláusulas `elif`. Se houver uma cláusula `else`, ela precisa estar no final, mas não precisa haver uma.

Cada condição é verificada em ordem. Se a primeira for falsa, a próxima é verificada e assim por diante. Se uma delas for verdadeira, o desvio correspondente é executado e a instrução `if` termina. Mesmo que mais de uma condição seja verdadeira, apenas o primeiro desvio verdadeiro é executado.

### 4.7. Condicionais Aninhados

Uma condicional também pode ser aninhada dentro de outra. Poderíamos ter escrito o exemplo da seção anterior assim:

In [188]:
if x == y:
    print('x e y são iguais')
else:
    if x < y:
        print('x é menor que y')
    else:
        print('x e y são iguais')

x é menor que y


A instrução `if` externa contém dois desvios/ramos. O primeiro desvio/ramo contém uma instrução simples. O segundo desvio/ramo contém outra instrução `if`, que possui dois desvios/ramos próprios. Esses dois desvios/ramos são instruções simples, embora também pudessem ser instruções condicionais.

Embora a indentação das instruções torne a estrutura aparente, **condicionais aninhadas** podem ser difíceis de ler.

Operadores lógicos geralmente fornecem uma maneira de simplificar instruções condicionais aninhadas. Aqui está um exemplo com uma condicional aninhada.

In [189]:
if 0 < x:
    if x < 10:
        print('x é um número positivo de um único dígito.')

x é um número positivo de um único dígito.


A instrução `print` só será executada se passarmos por ambas as condicionais, então obtemos o mesmo efeito com o operador `and`.

In [190]:
if 0 < x and x < 10:
    print('x é um número positivo de um único dígito.')

x é um número positivo de um único dígito.


Para esse tipo de condição, o Python fornece uma opção mais concisa:

In [191]:
if 0 < x < 10:
    print('x é um número positivo de um único dígito.')

x é um número positivo de um único dígito.


### 4.8. Recursão

É legal que uma função chame a si mesma. Pode não ser óbvio por que isso é bom, mas acaba sendo uma das coisas mais mágicas que um programa pode fazer. Aqui está um exemplo.

In [192]:
def countdown(n):
    if n <= 0:
        print('Decolagem!')
    else:
        print(n)
        countdown(n-1)

Se `n` for `0` ou negativo, `countdown` emite a palavra "Decolagem!". Caso contrário, ela imprime `n` e então chama a si mesmo, passando `n-1` como argumento.

Veja o que acontece quando chamamos esta função com o argumento `3`.

In [193]:
countdown(3)

3
2
1
Decolagem!


A execução de `countdown` começa com `n=3` e, como `n` é maior
que `0`, exibe `3` e, em seguida, chama a si mesmo\...

> A execução de `countdown` começa com `n=2` e, como `n` é
> maior que `0`, exibe `2` e, em seguida, chama a si mesmo\...
>
> > A execução de `countdown` começa com `n=1` e, como `n` é
> > maior que `0`, exibe `1` e, em seguida, chama a si mesmo\...
> >
> > > A execução de `countdown` começa com `n=0` e, como `n` não é
> > > maior que `0`, exibe "Decolagem!" e retorna.
> >
> > A `countdown` que obteve `n=1` retorna.
>
> A `countdown` que obteve `n=2` retorna.

A `countdown` que obteve `n=3` retorna.

Uma função que chama a si mesma é **recursiva**. Como outro exemplo, podemos escrever uma função que imprime uma string `n` vezes.

In [194]:
def print_n_vezes(string, n):
    if n > 0:
        print(string)
        print_n_vezes(string, n-1)

Se `n` for positivo, `print_n_vezes` exibe o valor de `string` e, em seguida, chama a si mesma, passando `string` e `n-1` como argumentos.

Se `n` for `0` ou negativo, a condição é falsa e `print_n_vezes` não faz nada.

Veja como funciona.

In [195]:
print_n_vezes('Spam', 4)

Spam
Spam
Spam
Spam


Para exemplos simples como este, provavelmente é mais fácil usar um laço `for`. Mas veremos exemplos mais adiante que são difíceis de escrever com um laço `for` e fáceis de escrever com recursão, então é bom começar cedo.

### 4.9. Recursão com Valores de Retorno

Agora que podemos escrever funções com valores de retorno, podemos escrever funções recursivas com valores de retorno e, com essa capacidade, ultrapassamos um limite importante: o subconjunto do Python que temos agora é Turing completo, o que significa que podemos executar qualquer computação que possa ser descrita por um algoritmo.

Para demonstrar recursão com valores de retorno, avaliaremos algumas funções matemáticas definidas recursivamente. Uma definição recursiva é semelhante a uma definição circular, no sentido de que a definição se refere ao objeto que está sendo definido.

A definição da função fatorial, denotada pelo símbolo $!$, pode ser definida como segue:

$$\begin{aligned}
0! &= 1 \\
n! &= n~(n-1)!
\end{aligned}$$ 

Esta definição diz que o fatorial de $0$ é $1$, e o fatorial de qualquer outro valor, $n$, é $n$ multiplicado pelo fatorial de $n-1$.

Se você consegue escrever uma definição recursiva de algo, você consegue escrever um programa em Python para avaliá-la. Seguindo um processo de desenvolvimento incremental, começaremos com uma função que recebe `n` como parâmetro e sempre retorna `0`.

In [196]:
def fatorial(n):
    return 0

Agora vamos adicionar a primeira parte da definição – se o argumento for `0`, tudo o que precisamos fazer é retornar `1`:

In [197]:
def fatorial(n):
    if n == 0:
        return 1
    else:
        return 0

Agora vamos preencher a segunda parte – se `n` não for `0`, temos que fazer uma chamada recursiva para encontrar o fatorial de `n-1` e então multiplicar o resultado por `n`:

In [198]:
def fatorial(n):
    if n == 0:
        return 1
    else:
        return n * fatorial(n-1)

Se chamarmos `fatorial` com o valor `3`:

Como `3` não é `0`, pegamos o segundo ramo e calculamos o fatorial
de `n-1`\...

> Como `2` não é `0`, pegamos o segundo ramo e calculamos o
> fatorial de `n-1`\...
>
> > Como `1` não é `0`, pegamos o segundo ramo e calculamos o
> > fatorial de `n-1`\...
> >
> > > Como `0` é igual a `0`, pegamos o primeiro ramo e retornamos `1` sem
> > > fazer mais chamadas recursivas.
> >
> > O valor de retorno, `1`, é multiplicado por `n`, que é `1`, e o
> > resultado é retornado.
>
> O valor de retorno, `1`, é multiplicado por `n`, que é `2`, e o resultado
> é retornado.

O valor de retorno `2` é multiplicado por `n`, que é `3`, e o resultado,
`6`, torna-se o valor de retorno da chamada de função que iniciou todo o
processo.

### 4.10. Recursão Infinita

Se uma recursão nunca atingir um caso base, ela continuará fazendo chamadas recursivas para sempre, e o programa nunca terminará. Isso é conhecido como **recursão infinita** e geralmente não é uma boa ideia. Aqui está uma função mínima com recursão infinita.

In [199]:
def recursivo():
    recursivo()

Cada vez que `recursivo` é chamado, ele chama a si mesmo, o que cria outro quadro. Em Python, há um limite para o número de *frames* que podem estar na *pilha* ao mesmo tempo. Se um programa exceder o limite, ocorrerá um erro de execução.

In [200]:
recursivo()

RecursionError: maximum recursion depth exceeded

O traceback indica que havia quase 3000 frames na pilha quando o erro ocorreu.

Se você encontrar uma recursão infinita por acidente, revise sua função para confirmar se há um caso base que não faça uma chamada recursiva. E se houver um caso base, verifique se há garantia de que você o alcançará.

### 4.11. Entrada via Teclado

Os programas que escrevemos até agora não aceitam entrada do usuário. Eles simplesmente fazem a mesma coisa todas as vezes.

O Python fornece uma função interna chamada `input` que interrompe o programa e aguarda que o usuário digite algo. Quando o usuário pressiona *Return ou Enter*, o programa é reiniciado e o `input` retorna o que o usuário digitou como uma string.

In [201]:
texto = input()

Antes de receber a entrada do usuário, você pode querer exibir um *prompt* informando ao usuário o que digitar. A entrada pode receber um *prompt* como argumento:

In [203]:
nome = input('Qual é o seu nome?\n')
nome

'Samuel'

A sequência `\n` no final do prompt representa uma **nova linha**, que é um caractere especial que causa uma quebra de linha – dessa forma, a entrada do usuário aparece abaixo do prompt.

Se você espera que o usuário digite um inteiro, pode usar a função `int` para converter o valor de retorno para `int`.

In [206]:
prompt = 'Qual é a velocidade de uma andorinha sem carga?\n'
velocidade = input(prompt)
velocidade

'a'

Mas se eles digitarem algo que não seja um inteiro, você receberá um erro de tempo de execução.

In [207]:
int(velocidade)

ValueError: invalid literal for int() with base 10: 'a'

Veremos como lidar com esse tipo de erro mais tarde.

### 4.12. Exercícios

In [208]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

Exception reporting mode: Verbose


#### 4.12.1 Exercício

O módulo `time` fornece uma função, também chamada `time`, que retorna o número de segundos desde a "época Unix", que é 1º de janeiro de 1970, 00:00:00 UTC (Tempo Universal Coordenado).

In [12]:
from time import time

now = time()
now

1788186617.009079

Use a divisão inteira e o operador de módulo para calcular o número de dias desde 1º de janeiro de 1970 e a hora atual em horas, minutos e segundos.

Você pode ler mais sobre o módulo time em [https://docs.python.org/3/library/time.html](https://docs.python.org/3/library/time.html).

In [13]:
segundos = int(now)
print('Passaram-se', segundos, 'segundos desde 1º de janeiro de 1970')
minutos = now // 60
print('Passaram-se', int(minutos), 'minutos desde 1º de janeiro de 1970')
horas = minutos // 60
print('Passaram-se', int(horas), 'horas desde 1º de janeiro de 1970')
dias = horas // 24
print('Passaram-se', int(dias), 'dias desde 1º de janeiro de 1970')

Passaram-se 1788186617 segundos desde 1º de janeiro de 1970
Passaram-se 29803110 minutos desde 1º de janeiro de 1970
Passaram-se 496718 horas desde 1º de janeiro de 1970
Passaram-se 20696 dias desde 1º de janeiro de 1970


In [14]:
print(horas % 24)
print(minutos % 60)
print(segundos % 60)

14.0
30.0
17


In [30]:
from time import time

def passed_time(now: float) -> None:
    """Utiliza o tempo em segundos decorrido desde 1º de janeiro de 1970 a partir da biblioteca time e
    demonstra o número de dias passados desde então e também a hora, minuto e segundos
    
    now: tempo decorrido em segundos desde 1º de Janeiro de 1970
    """
    minutos = now // 60
    horas = minutos // 60
    dias = horas // 24

    print('Passaram-se', int(dias), 'dias desde 1º de janeiro de 1970')
    print('São', int(horas % 24), ':', int(minutos % 60), ':', int(now % 60), 'em UTC')

now = time()
passed_time(now)

Passaram-se 20696 dias desde 1º de janeiro de 1970
São 14 : 53 : 45 em UTC


#### 4.12.2 Exercício

Se você receber três varetas, poderá ou não conseguir organizá-las em um triângulo. Por exemplo, se uma das varetas tiver 30cm de comprimento e as outras duas tiverem 2.5cm, você não conseguirá que as varetas curtas se encontrem no meio. Para quaisquer três comprimentos, existe um teste para verificar se é possível formar um triângulo:

> Se qualquer um dos três comprimentos for maior que a soma dos outros dois,
> então você não pode formar um triângulo. Caso contrário, você pode. (Se a soma de
> dois comprimentos for igual ao terceiro, eles formam o que é chamado de triângulo
> "degenerado".)

Escreva uma função chamada `is_triangle` que receba três inteiros como argumentos e que imprima "Sim" ou "Não", dependendo se você consegue ou não formar um triângulo com varetas com os comprimentos fornecidos. Dica: Use uma condicional encadeada.

In [29]:
def is_triangle(l1: int, l2: int, l3: int) -> str:
    """Recebe trẽs inteiros e retorna se é possível ou não formar um triângulo a partir do valor desses inteiros como comprimentos dos lados de um triângulo
    
    l1, l2, l3: valor dos possíveis lados do triângulo
    """
    soma_l1_l2 = l1 + l2
    soma_l1_l3 = l1 + l3
    soma_l2_l3 = l2 + l3

    if l1 > soma_l2_l3 or l2 > soma_l1_l3 or l3 > soma_l1_l2:
        return 'Não'
    elif l1 == soma_l2_l3 or l2 == soma_l1_l3 or l3 == soma_l1_l2:
        return 'Triângulo Degenerado'
    else:
        return 'Sim'

is_triangle(25, 24, 2)

'Sim'

#### 4.12.3 Exercício

Depois do fatorial, o exemplo mais comum de uma função recursiva é Fibonacci, que tem a seguinte definição:

$$\begin{aligned}
\mathrm{fibonacci}(0) &= 0 \\
\mathrm{fibonacci}(1) &= 1 \\
\mathrm{fibonacci}(n) &= \mathrm{fibonacci}(n-1) + \mathrm{fibonacci}(n-2)
\end{aligned}$$

Implemente uma versão recursiva de `fibonacci` em Python.

In [ ]:
def fibonacci(n: int) -> int:
    """Retorna o n-ésimo valor da Sequência de Fibonacci
    
    n: posição na Sequência de Fibonacci cujo valor será retornado
    """
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

fibonacci(6)

8

## 5. Strings e Expressões Regulares

Strings não são como inteiros, floats e booleanos. Uma string é uma sequência, o que significa que contém vários valores em uma ordem específica. Nesta seção, veremos como acessar os valores que compõem uma string e usaremos funções que processam strings.

Também usaremos expressões regulares, que são uma ferramenta poderosa para encontrar padrões em uma string e realizar operações como localizar e substituir.

### 5.1. Uma string é uma Sequência

Uma string é uma sequência de caracteres. Um **caractere** pode ser uma letra (em quase qualquer alfabeto), um dígito, um sinal de pontuação ou um espaço em branco.

Você pode selecionar um caractere de uma string com o operador de colchetes. Esta instrução de exemplo seleciona o caractere número 1 de `fruta` e o atribui a uma `letra`:

In [38]:
fruta = 'banana'
letra = fruta[1]

A expressão entre parênteses é um **índice**, assim chamado porque indica qual caractere na sequência selecionar. Mas o resultado pode não ser o esperado.

In [39]:
letra

'a'

A letra com índice `1` é, na verdade, a segunda letra da string. Um índice é um deslocamento do início da string, portanto, o deslocamento da primeira letra é `0`.

In [40]:
fruta[0]

'b'

Você pode pensar em "b" como a letra `0` de "banana" – pronuncia-se "zero-eth" ou "zerésima".

O índice entre colchetes pode ser uma variável.

In [41]:
i = 1
fruta[i]

'a'

Ou uma expressão que contém variáveis ​​e operadores.

In [42]:
fruta[i+1]

'n'

Mas o valor do índice tem que ser um inteiro – caso contrário, você receberá um `TypeError`.

In [43]:
fruta[1.5]

TypeError: string indices must be integers, not 'float'

Podemos usar a função interna `len` para obter o comprimento de uma string.

In [44]:
n = len(fruta)
n

6

Para obter a última letra de uma string, você pode ficar tentado a escrever isto:

In [45]:
fruta[n]

IndexError: string index out of range

Mas isso causa um `IndexError` porque não há nenhuma letra em `'banana'` com índice 6. Como começamos a contar em `0`, as seis letras são numeradas de `0` a `5`. Para obter o último caractere, você precisa subtrair `1` de `n`:

In [46]:
fruta[n-1]

'a'

Mas existe uma maneira mais fácil. Para obter a última letra de uma string, você pode usar um índice negativo, que conta de trás para frente a partir do final.

In [47]:
fruta[-1]

'a'

O índice `-1` seleciona a última letra, `-2` seleciona a penúltima e assim por diante.

### 5.2. Fatiamento de Strings

Um segmento de uma string é chamado de **fatia**. Selecionar uma fatia é semelhante a selecionar um caractere.

In [48]:
fruta = 'banana'
fruta[0:3]

'ban'

O operador `[n:m]` retorna a parte da string do `n-ésimo` caractere ao `m-ésimo` caractere, incluindo o primeiro, mas excluindo o segundo. Esse comportamento é contraintuitivo, mas pode ajudar imaginar os índices apontando entre os caracteres.

Por exemplo, a fatia `[3:6]` seleciona as letras `ana`, o que significa que `6` é válido como parte de uma fatia, mas não como índice.

Se você omitir o primeiro índice, a fatia começará no início da string.

In [49]:
fruta[:3]

'ban'

Se você omitir o segundo índice, a fatia vai para o final da string:

In [50]:
fruta[3:]

'ana'

Se o primeiro índice for maior ou igual ao segundo, o resultado será uma string vazia, representada por duas aspas:

In [51]:
fruta[3:3]

''

Uma string vazia não contém caracteres e tem comprimento 0.

Continuando com este exemplo, o que você acha que `fruta[:]` significa? Experimente e veja.

In [52]:
fruta[:]

'banana'

### 5.3. Strings são Imutáveis

É tentador usar o operador `[]` no lado esquerdo de uma atribuição, com a intenção de alterar um caractere em uma string, assim:

In [53]:
saudacao = 'Olá, mundo!'
saudacao[0] = 'J'

TypeError: 'str' object does not support item assignment

O resultado é um `TypeError`. Na mensagem de erro, o "objeto" é a string e o "item" é o caractere que tentamos atribuir. Por enquanto, um **objeto** é o mesmo que um valor, mas refinaremos essa definição em outra seção.

O motivo desse erro é que strings são **imutáveis**, o que significa que você não pode alterar uma string existente. O melhor que você pode fazer é criar uma nova string que seja uma variação da original.

In [54]:
new_saudacao = 'J' + saudacao[1:]
new_saudacao

'Jlá, mundo!'

Este exemplo concatena uma nova primeira letra a uma parte da `saudacao`. Não tem efeito na string original.

In [55]:
saudacao

'Olá, mundo!'

In [56]:
saudacao = 'J' + saudacao[1:]
saudacao

'Jlá, mundo!'

### 5.4. Comparação de Strings

Os operadores relacionais funcionam com strings. Para verificar se duas strings são iguais, podemos usar o operador `==`.

In [57]:
palavra = 'banana'

if palavra == 'banana':
    print('Tudo bem, banana.')

Tudo bem, banana.


Outras operações relacionais são úteis para colocar palavras em ordem alfabética:

In [58]:
def compara_palavra(palavra):
    if palavra < 'banana':
        print(palavra, 'vem antes de banana.')
    elif palavra > 'banana':
        print(palavra, 'vem depois de banana')
    else:
        print('Tudo bem, banana.')

In [59]:
compara_palavra('abacaxi')

abacaxi vem antes de banana.


O Python não lida com letras maiúsculas e minúsculas da mesma forma que as pessoas. Todas as letras maiúsculas vêm antes das minúsculas, então:

In [60]:
compara_palavra('Maçã')

Maçã vem antes de banana.


Para resolver esse problema, podemos converter strings para um formato padrão, como todas em minúsculas, antes de realizar a comparação.

### 5.5. Métodos da String

Strings fornecem métodos que realizam uma variedade de operações úteis. Um método é semelhante a uma função – recebe argumentos e retorna um valor – mas a sintaxe é diferente. Por exemplo, o método `upper` recebe uma string e retorna uma nova string com todas as letras maiúsculas.

Em vez da sintaxe da função `upper(palavra)`, ele usa a sintaxe do método `palavra.upper()`.

In [61]:
palavra = 'banana'
new_palavra = palavra.upper()
new_palavra

'BANANA'

Este uso do operador ponto especifica o nome do método, `upper`, e o nome da string à qual o método será aplicado, `palavra`. Os parênteses vazios indicam que este método não aceita argumentos.

Uma chamada de método é chamada de **invocação**; neste caso, diríamos que estamos invocando `upper` em `palavra`.

Similar a `upper`, temos também o método `lower`, que retorna uma nova string com todas as letras minúsculas. Veja o exemplo abaixo:

In [62]:
print(new_palavra)
print(new_palavra.lower())

BANANA
banana


Todos os métodos de strings podem ser vistos na [documentação oficial](https://docs.python.org/pt-br/3/library/stdtypes.html#string-methods) do Python.

### 5.6. Escrevendo Arquivos

Operadores e métodos de string são úteis para ler e escrever arquivos de texto. Como exemplo, trabalharemos com o texto de Drácula, um romance de Bram Stoker disponível no [Projeto Gutenberg](https://www.gutenberg.org/ebooks/345).

Baixei o livro em um arquivo de texto simples chamado [pg345.txt](https://www.gutenberg.org/cache/epub/345/pg345.txt), que podemos abrir para leitura assim:

In [ ]:
reader = open('./files/pg345.txt')

Além do texto do livro, este arquivo contém uma seção no início com informações sobre o livro e uma seção no final com informações sobre a licença. Antes de processarmos o texto, podemos remover esse material extra encontrando as linhas especiais no início e no final que começam com `'***'`.

A função a seguir recebe uma linha e verifica se ela é uma das linhas especiais. Ela usa o método `startswith`, que verifica se uma string começa com uma determinada sequência de caracteres.

In [ ]:
def is_special_line(line):
    return line.startswith('*** ')

Podemos usar esta função para percorrer as linhas do arquivo e imprimir apenas as linhas especiais.

In [ ]:
for line in reader:
    if is_special_line(line):
        print(line.strip())

Agora, vamos criar um novo arquivo, chamado `pg345_cleaned.txt`, que contém apenas o texto do livro. Para percorrer o livro novamente, precisamos abri-lo novamente para leitura. E, para escrever um novo arquivo, podemos abri-lo para escrita.

In [ ]:
reader = open('./files/pg345.txt')
writer = open('./files/pg345_cleaned.txt', 'w')

`open` recebe um parâmetro opcional que especifica o "modo" – neste exemplo, `'w'` indica que estamos abrindo o arquivo para escrita. Se o arquivo não existir, ele será criado; se já existir, o conteúdo será substituído.

Como primeiro passo, percorreremos o arquivo até encontrarmos a primeira linha especial.

In [ ]:
for line in reader:
    if is_special_line(line):
        break

A instrução `break` "sai" do loop, ou seja, faz com que o loop termine imediatamente, antes de chegarmos ao final do arquivo.

Quando o loop termina, line contém a `line` especial que tornou a condicional verdadeira.

In [ ]:
line

Como o `reader` mantém o controle de onde está no arquivo, podemos usar um segundo loop para continuar de onde paramos.

O loop seguinte lê o restante do arquivo, uma linha de cada vez. Ao encontrar a linha especial que indica o fim do texto, ele sai do loop. Caso contrário, ele grava a linha no arquivo de saída.

In [ ]:
for line in reader:
    if is_special_line(line):
        break
    writer.write(line)

Quando esse loop termina, `line` contém a segunda linha especial.

In [ ]:
line

Neste ponto, o `reader` e o `writer` ainda estão abertos, o que significa que podemos continuar lendo linhas do `reader` ou escrevendo linhas para o `writer`. Para indicar que terminamos, podemos fechar ambos os arquivos invocando o método `close`.

In [ ]:
reader.close()
writer.close()

Para verificar se esse processo foi bem-sucedido, podemos ler as primeiras linhas do novo arquivo que acabamos de criar.

In [ ]:
for line in open('./files/pg345_cleaned.txt'):
    line = line.strip()
    if len(line) > 0:
        print(line)
    if line.endswith('Stoker'):
        break

O método `endswith` verifica se uma string termina com uma determinada sequência de caracteres.

### 5.7. Localizar e Substituir

Na tradução islandesa de *Drácula* de 1901, o nome de um dos personagens foi alterado de "Jonathan" para "Thomas". Para fazer essa alteração na versão em inglês, podemos percorrer o livro em loop, usar o método replace para substituir um nome por outro e gravar o resultado em um novo arquivo.

Começaremos contando as linhas na versão limpa do arquivo.

In [ ]:
total = 0
for line in open('./files/pg345_cleaned.txt'):
    total += 1
    
total

Para ver se uma linha contém “Jonathan”, podemos usar o operador `in`, que verifica se essa sequência de caracteres aparece em algum lugar da linha.

In [ ]:
total = 0
for line in open('./files/pg345_cleaned.txt'):
    if 'Jonathan' in line:
        total += 1

total

Há 199 linhas que contêm o nome, mas esse não é o número total de vezes que ele aparece, pois pode aparecer mais de uma vez em uma linha. Para obter o total, podemos usar o método `count`, que retorna o número de vezes que uma sequência aparece em uma string.

In [ ]:
total = 0
for line in open('./files/pg345_cleaned.txt'):
    total += line.count('Jonathan')

total

Agora podemos substituir `'Jonathan'` por `'Thomas'` assim:

In [ ]:
writer = open('./files/pg345_replaced.txt', 'w')

for line in open('./files/pg345_cleaned.txt'):
    line = line.replace('Jonathan', 'Thomas')
    writer.write(line)

O resultado é um novo arquivo chamado `pg345_replaced.txt` que contém uma versão de Drácula onde `Jonathan Harker` é chamado de `Thomas`.

### 5.8. Expressões Regulares

Se soubermos exatamente qual sequência de caracteres estamos procurando, podemos usar o operador `in` para encontrá-la e o método `replace` para substituí-la. Mas existe outra ferramenta, chamada expressão regular, que também pode realizar essas operações – e muito mais.

Para demonstrar, começarei com um exemplo simples e avançaremos. Suponha, novamente, que queremos encontrar todas as linhas que contêm uma palavra específica. Para variar, vamos procurar referências ao personagem-título do livro, o Conde Drácula. Aqui está uma linha que o menciona.

In [ ]:
texto = "I am Dracula; and I bid you welcome, Mr. Harker, to my house."

E aqui está o padrão que usaremos para pesquisar.

In [ ]:
pattern = 'Dracula'

Um módulo chamado `re` fornece funções relacionadas a expressões regulares. Podemos importá-lo assim e usar a função de `search` para verificar se o padrão aparece no texto.

In [ ]:
import re

result = re.search(pattern, texto)
result

Se o padrão aparecer no texto, `search` retornará um objeto `Match` que contém os resultados da pesquisa. Entre outras informações, ele possui uma variável chamada `string` que contém o texto pesquisado.

In [ ]:
result.string

Ele também fornece um método chamado `group` que retorna a parte do texto que corresponde ao padrão.

In [ ]:
result.group()

E fornece um método chamado `span` que retorna o índice no texto onde o padrão começa e termina.

In [ ]:
result.span()

Se o padrão não aparecer no texto, o valor de retorno de `search` será `None`.

In [ ]:
result = re.search('Count', texto)
print(result)

Juntando tudo isso, aqui está uma função que percorre as linhas do livro até encontrar uma que corresponda ao padrão fornecido e retorna o objeto `Match`.

In [ ]:
def find_first(pattern):
    for line in open('./files/pg345_cleaned.txt'):
        result = re.search(pattern, line)
        if result != None:
            return result

Podemos usá-lo para encontrar a primeira menção de um personagem.

In [ ]:
result = find_first('Harker')
result.string

Neste exemplo, não precisamos usar expressões regulares – poderíamos ter feito a mesma coisa mais facilmente com o operador `in`. Mas expressões regulares podem fazer coisas que o operador `in` não pode.

Por exemplo, se o padrão incluir o caractere de barra vertical, `'|'`, ele pode corresponder à sequência à esquerda ou à sequência à direita. Suponha que queremos encontrar a primeira menção de Mina Murray no livro, mas não temos certeza se ela é mencionada pelo primeiro nome ou pelo sobrenome. Podemos usar o padrão a seguir, que corresponde a qualquer um dos nomes.

In [ ]:
pattern = 'Mina|Murray'
result = find_first(pattern)
result.string

Podemos usar um padrão como este para ver quantas vezes um personagem é mencionado por qualquer nome. Aqui está uma função que percorre o livro e conta o número de linhas que correspondem ao padrão fornecido.

In [ ]:
def count_matches(pattern):
    count = 0
    for line in open('./files/pg345_cleaned.txt'):
        result = re.search(pattern, line)
        if result != None:
            count += 1
    return count

Agora vamos ver quantas vezes Mina é mencionada.

In [ ]:
count_matches('Mina|Murray')

O caractere especial `'^'` corresponde ao início de uma string, então podemos encontrar uma linha que começa com um padrão determinado.

In [ ]:
result = find_first('^Dracula')
result.string

E o caractere especial `'$'` corresponde ao final de uma string, então podemos encontrar uma linha que termina com um padrão dado (ignorando a nova linha no final).

In [ ]:
result = find_first('Harker$')
result.string

### 5.9. Substituição de Strings

Bram Stoker nasceu na Irlanda e, quando *Drácula* foi publicado em 1897, ele morava na Inglaterra. Portanto, esperaríamos que ele usasse a grafia britânica de palavras como "centre" e "colour". Para verificar, podemos usar o seguinte padrão, que corresponde a "centre" ou à grafia americana "center".

In [ ]:
pattern = 'cent(er|re)'

Neste padrão, os parênteses delimitam a parte do padrão à qual a barra vertical se aplica. Portanto, este padrão corresponde a uma sequência que começa com `"cent"` e termina com `"er"` ou `"re"`.

In [ ]:
result = find_first(pattern)
result.string

Como esperado, ele usou a grafia britânica.

Também podemos verificar se ele usou a grafia britânica de "colour". O padrão a seguir usa o caractere especial `'?'`, o que significa que o caractere anterior é opcional.

In [ ]:
pattern = 'colou?r'

Este padrão combina "colour" com o `'u'` ou "color" sem ele.

In [ ]:
result = find_first(pattern)
line = result.string
line

Novamente, como esperado, ele usou a grafia britânica.

Agora, suponha que queremos produzir uma edição do livro com a grafia americana. Podemos usar a função `sub` no módulo `re`, que faz a **substituição de strings**.

In [ ]:
re.sub(pattern, 'color', line)

O primeiro argumento é o padrão que queremos encontrar e substituir, o segundo é o que queremos usar para substituí-lo e o terceiro é a string que queremos pesquisar. No resultado, você pode ver que "colour" foi substituído por "color".

### 5.10. Exercícios

In [ ]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

#### 5.10.1. Exercício

Escreva um comando `print()` usando a string `s` e o conceito de **fatiamento** de strings, tal que seja mostrado o resultado esperado.

In [ ]:
s = "0123456789"

Resultado esperado: `'234'`

In [ ]:
# escreva aqui sua resposta

Resultado esperado: `'012789'`

In [ ]:
# escreva aqui sua resposta

Resultado esperado: `'789'`

In [ ]:
# escreva aqui sua resposta

#### 5.10.2. Exercício

Escreva uma função que receba um endereço de e-mail (string) como entrada e substitua as ocorrências do caractere `'@'` por `'<at>'`' e do caractere `'.'` por `'<dot>'` e retorne a string alterada. O retorno da função deve ser impresso. Por exemplo, dado um e-mail `'aluno@alu.ufc.br'` como entrada, o programa deve processá-lo de tal modo que seja impresso `'aluno<at>alu<dot>ufc<dot>br'`.

In [ ]:
# escreva aqui sua resposta

#### 5.10.3. Exercício

Veja se você consegue escrever uma função que faça a mesma coisa que o comando shell [`head`](https://guialinux.uniriotec.br/head/). Ela deve receber como argumentos o nome de um arquivo a ser lido, o número de linhas a serem lidas e o nome do arquivo no qual as linhas serão gravadas. Se o terceiro parâmetro for `None`, ela deve exibir as linhas em vez de gravá-las em um arquivo.

In [ ]:
# escreva aqui sua resposta

#### 5.10.4. Exercício

O *Conde de Monte Cristo* é um romance de Alexandre Dumas considerado um clássico. No entanto, na introdução de uma tradução em inglês do livro, o escritor Umberto Eco confessa que considerou o livro "um dos romances mais mal escritos de todos os tempos".

Em particular, ele diz que é "descarado na repetição do mesmo adjetivo" e menciona, em particular, o número de vezes que "seus personagens estremecem ou empalidecem".

Para verificar se sua objeção é válida, vamos contar o número de linhas que contêm a palavra `"pale"` em qualquer forma, incluindo `"pale"`, `"pales"`, `"paled"` e `"paleness"`, bem como a palavra relacionada `"pallor"`. Use uma única expressão regular que corresponda a qualquer uma dessas palavras.

O arquivo texto do livro por ser baixado diretamente: [pg1184.txt](https://www.gutenberg.org/cache/epub/1184/pg1184.txt).

**Desafio**: Altere sua resposta para evitar que palavras como `"impale"` seja considerada. **Dica!** Mostre seu código ao assistente virtual e peça uma sugestão.

In [ ]:
# escreva aqui sua resposta

## 6. Listas, Dicionários e Tuplas

Esta seção apresenta as principais estruturas de dados nativas do Python: listas, dicionários e tuplas.

### 6.1. Listas

#### 6.1.1. Uma Lista é uma Sequência

Assim como uma string, uma lista é uma sequência de valores. Em uma string, os valores são caracteres; em uma lista, eles podem ser de qualquer tipo. Os valores em uma lista são chamados de **elementos**.

Existem várias maneiras de criar uma nova lista; a mais simples é colocar os elementos entre colchetes (`[` e `]`). Por exemplo, aqui está uma lista de dois inteiros.

In [18]:
numeros = [42, 123]
numeros

[42, 123]

E aqui está uma lista de três strings.

In [19]:
queijos = ['Cheddar', 'Edam', 'Gouda']
queijos

['Cheddar', 'Edam', 'Gouda']

Os elementos de uma lista não precisam ser do mesmo tipo. A lista a seguir contém uma string, um float, um inteiro e até mesmo outra lista.

In [21]:
t = ['spam', 2.0, 5, [10, 20]]
t

['spam', 2.0, 5, [10, 20]]

Uma lista dentro de outra lista é **aninhada**.

Uma lista que não contém elementos é chamada de lista vazia; você pode criar uma com colchetes vazios, `[]`.

In [22]:
vazia = []
vazia

[]

A função `len` retorna o comprimento de uma lista.

In [23]:
len(queijos)

3

O comprimento de uma lista `vazia` é `0`.

#### 6.1.2. Listas são Mutáveis

Para ler um elemento de uma lista, podemos usar o operador de colchetes. O índice do primeiro elemento é `0`.

In [24]:
queijos[0]

'Cheddar'

Ao contrário das strings, as listas são mutáveis. Quando o operador de colchetes aparece à esquerda de uma atribuição, ele identifica o elemento da lista que será atribuído.

In [25]:
numeros[1] = 17
numeros

[42, 17]

O segundo elemento de `numeros`, que costumava ser `123`, agora é `17`.

Índices de lista funcionam da mesma forma que índices de string:

- Qualquer expressão inteira pode ser usada como índice.

- Se você tentar ler ou escrever um elemento que não existe, receberá um `IndexError`.

- Se um índice tiver um valor negativo, ele conta para trás a partir do final da lista.

O operador `in` funciona em listas – ele verifica se um determinado elemento aparece em algum lugar da lista.

In [26]:
'Edam' in queijos

True

In [27]:
'Wensleydale' in queijos

False

Embora uma lista possa conter outra lista, a lista aninhada ainda conta como um único elemento – portanto, na lista a seguir, há apenas quatro elementos.

In [28]:
t = ['spam', 2.0, 5, [10, 20]]
len(t)

4

E `10` não é considerado um elemento de `t` porque é um elemento de uma lista aninhada, não `t`.

In [ ]:
10 in t

[10, 20]


#### 6.1.3. Fatias de Lista

O operador de fatiamento funciona em listas da mesma forma que em strings. O exemplo a seguir seleciona o segundo e o terceiro elementos de uma lista de quatro letras.

In [41]:
letras = ['a', 'b', 'c', 'd']
letras[1:3]

['b', 'c']

Se você omitir o primeiro índice, a fatia começará do início.

In [42]:
letras[:2]

['a', 'b']

Se você omitir o segundo, a fatia vai para o final.

In [43]:
letras[2:]

['c', 'd']

Então, se você omitir ambos, a fatia será uma cópia da lista inteira.

In [44]:
letras[:]

['a', 'b', 'c', 'd']

Outra maneira de copiar uma lista é usar a função `list`.

In [47]:
list(letras)

['a', 'b', 'c', 'd']

Como `list` é o nome de uma função interna, você deve evitar usá-la como nome de variável.

#### 6.1.4. Operações com Lista

O operador `+` concatena listas.

In [48]:
t1 = [1,2]
t2 = [3,4]
t1 + t2

[1, 2, 3, 4]

O operador `*` repete uma lista um determinado número de vezes.

In [51]:
['spam'] * 4

['spam', 'spam', 'spam', 'spam']

Nenhum outro operador matemático funciona com listas, mas a função interna `sum` soma os elementos.

In [52]:
sum(t1)

3

E `min` e `max` encontram os menores e maiores elementos.

In [53]:
min(t1)

1

In [54]:
max(t2)

4

#### 6.1.5. Métodos de Lista

Python fornece métodos que operam em listas. Por exemplo, `append` adiciona um novo elemento ao final de uma lista:

In [55]:
letras.append('e')
letras

['a', 'b', 'c', 'd', 'e']

`extend` recebe uma lista como argumento e anexa todos os elementos:

In [56]:
letras.extend(['f', 'g'])
letras

['a', 'b', 'c', 'd', 'e', 'f', 'g']

Existem dois métodos para remover elementos de uma lista. Se você souber o índice do elemento desejado, pode usar `pop`.

In [57]:
t = ['a', 'b', 'c']
t.pop(1)

'b'

O valor de retorno é o elemento que foi removido. E podemos confirmar que a lista foi modificada.

In [58]:
t

['a', 'c']

Se você sabe o elemento que deseja remover (mas não o índice), você pode usar `remove`:

In [59]:
t = ['a', 'b', 'c']
t.remove('b')

O valor de retorno de remove é `None`. Mas podemos confirmar que a lista foi modificada.

In [60]:
t

['a', 'c']

Se o elemento solicitado não estiver na lista, isso é um `ValueError`.

In [61]:
t.remove('d')

ValueError: list.remove(x): x not in list

#### 6.1.6. Lista e Strings

Uma string é uma sequência de caracteres e uma lista é uma sequência de valores, mas uma lista de caracteres não é o mesmo que uma string. Para converter uma string para uma lista de caracteres, você pode usar a função `list`.

In [ ]:
s = 'spam'
t = list(s)
t

['s', 'p', 'a', 'm', ' ', 'o', 'l', 'a']

A função `list` divide uma string em letras individuais. Se você quiser dividir uma string em palavras, pode usar o método `split`:

In [64]:
s = 'pining for the fjords'
t = s.split()
t

['pining', 'for', 'the', 'fjords']

Um argumento opcional chamado **delimitador** especifica quais caracteres usar como limites de palavras. O exemplo a seguir usa um hífen como delimitador.

In [65]:
s = 'ex-parrot'
t = s.split('-')
t

['ex', 'parrot']

Se você tiver uma lista de strings, poderá concatená-las em uma única string usando `join`. `join` é um método de string, então você precisa invocá-lo no delimitador e passar a lista como um argumento.

In [66]:
delimiter = ' '
t = ['pining', 'for', 'the', 'fjords']
s = delimiter.join(t)
s

'pining for the fjords'

Neste caso, o delimitador é um caractere de espaço, então `join` coloca um espaço entre as palavras. Para unir strings sem espaços, você pode usar a string vazia '' como delimitador.

#### 6.1.7. Iterando sobre Listas

Você pode usar uma instrução `for` para percorrer os elementos de uma lista.

In [67]:
for queijo in queijos:
    print(queijo)

Cheddar
Edam
Gouda


Por exemplo, depois de usar `split` para criar uma lista de palavras, podemos usar `for` para percorrê-las.

In [68]:
s = 'pining for the fjords'

for palavra in s.split():
    print(palavra)

pining
for
the
fjords


Um loop `for` sobre uma lista vazia nunca executa as instruções recuadas.

In [69]:
for x in []:
    print('Isso nunca acontece.')

#### 6.1.8. Ordenando Listas

O Python fornece uma função interna chamada `sorted` que classifica os elementos de uma lista.

In [70]:
scramble = ['c', 'a', 'b']
sorted(scramble)

['a', 'b', 'c']

A lista original não foi alterada.

In [71]:
scramble

['c', 'a', 'b']

`sorted` funciona com qualquer tipo de sequência, não apenas com listas. Assim, podemos ordenar as letras em uma string assim.

In [72]:
sorted('letras')

['a', 'e', 'l', 'r', 's', 't']

O resultado é uma lista. Para converter a lista em uma string, podemos usar `join`.

In [73]:
''.join(sorted('letras'))

'aelrst'

Com uma string vazia como delimitador, os elementos da lista são unidos sem nada entre eles.

### 6.2. Dicionários

#### 6.2.1. Dicionários como Mapeamentos

Um **dicionário** é como uma lista, mas mais geral. Em uma lista, os índices precisam ser inteiros; em um dicionário, eles podem ser de (quase) qualquer tipo. Por exemplo, suponha que façamos uma lista de palavras numéricas, como esta.

In [74]:
lista = ['zero', 'um', 'dois']

Podemos usar um número inteiro como índice para obter a palavra correspondente.

In [75]:
lista[1]

'um'

Mas suponha que queiramos ir na outra direção e procurar uma palavra para obter o inteiro correspondente. Não podemos fazer isso com uma lista, mas podemos com um dicionário. Começaremos criando um dicionário vazio e atribuindo-lhe números.

In [76]:
numeros = {}
numeros

{}

As chaves, `{}`, representam um dicionário vazio. Para adicionar itens ao dicionário, usaremos colchetes.

In [ ]:
numeros['zero'] = 0

Esta atribuição adiciona ao dicionário um **item**, que representa a associação de uma **chave** e um **valor**. Neste exemplo, a chave é a string `'zero'` e o valor é o inteiro `0`. Se exibirmos o dicionário, veremos que ele contém um item, que contém uma chave e um valor separados por dois pontos, `:`.

In [78]:
numeros

{'zero': 0}

Podemos adicionar mais itens como este.

In [79]:
numeros['um'] = 1
numeros['dois'] = 2
numeros

{'zero': 0, 'um': 1, 'dois': 2}

Agora, o dicionário contém três itens.

Para consultar uma chave e obter o valor correspondente, usamos o operador de colchetes.

In [80]:
numeros['dois']

2

Se a chave não estiver no dicionário, obteremos um `KeyError`.

In [81]:
numeros['tres']

KeyError: 'tres'

A função `len` funciona em dicionários; ela retorna o número de itens.

In [82]:
len(numeros)

3

Em linguagem matemática, um dicionário representa um mapeamento de chaves para valores, então também podemos dizer que cada chave "mapeia" para um valor. Neste exemplo, cada palavra numérica mapeia para o inteiro correspondente.

#### 6.2.2. Criando Dicionários

Na seção anterior, criamos um dicionário vazio e adicionamos itens um de cada vez usando o operador de colchetes. Em vez disso, poderíamos ter criado o dicionário de uma só vez, assim.

In [84]:
numeros = {'zero': 0, 'um': 1, 'dois': 2}
numeros

{'zero': 0, 'um': 1, 'dois': 2}

Cada item consiste em uma chave e um valor separados por dois pontos. Os itens são separados por vírgulas e colocados entre chaves.

Outra maneira de criar um dicionário é usar a função `dict`. Podemos criar um dicionário vazio assim.

In [85]:
vazio = dict()
vazio

{}

E podemos fazer uma cópia de um dicionário como este.

In [86]:
numeros_copy = dict(numeros)
numeros_copy

{'zero': 0, 'um': 1, 'dois': 2}

Geralmente é útil fazer uma cópia antes de executar operações que modificam dicionários.

#### 6.2.3. Iterando sobre Dicionários

Se você usar um dicionário em uma instrução for, ele percorrerá as chaves do dicionário. Para demonstrar, vamos criar um dicionário que conte as letras de `'banana'`.

In [87]:
def value_counts(string):
    counter = {}
    for letra in string:
        if letra not in counter:
            counter[letra] = 1
        else:
            counter[letra] += 1
    return counter

In [88]:
counter = value_counts('banana')
counter

{'b': 1, 'a': 3, 'n': 2}

O loop a seguir imprime as chaves, que são as letras.

In [89]:
for key in counter:
    print(key)

b
a
n


Para imprimir os valores, podemos usar o método `values`.

In [90]:
for value in counter.values():
    print(value)

1
3
2


Para imprimir as chaves e os valores, podemos percorrer as chaves e procurar os valores correspondentes.

In [91]:
for key in counter:
    value = counter[key]
    print(key, value)

b 1
a 3
n 2


### 6.3. Tuplas

#### 6.2.1. Tuplas são Parecidas com Listas

Uma tupla é uma sequência de valores. Os valores podem ser de qualquer tipo e são indexados por números inteiros, portanto, tuplas são muito parecidas com listas. A diferença importante é que tuplas são imutáveis.

Para criar uma tupla, você pode escrever uma lista de valores separados por vírgulas.

In [93]:
t = 'l', 'u', 'p', 'i', 'n'
print(t)
type(t)

('l', 'u', 'p', 'i', 'n')


tuple

Embora não seja necessário, é comum colocar tuplas entre parênteses.

In [95]:
t = ('l', 'u', 'p', 'i', 'n')
print(t)
type(t)

('l', 'u', 'p', 'i', 'n')


tuple

Para criar uma tupla com um único elemento, você precisa incluir uma vírgula final.

In [97]:
t1 = 'p',
print(t1)
type(t1)

('p',)


tuple

Um único valor entre parênteses não é uma tupla.

In [101]:
t2 = ('p')
type(t2)

str

Outra maneira de criar uma tupla é com a função interna `tuple`. Sem argumentos, ela cria uma tupla vazia.

In [102]:
t = tuple()
t

()

Se o argumento for uma sequência (string, lista ou tupla), o resultado será uma tupla com os elementos da sequência.

In [112]:
t = tuple('lupin')
t

('l', 'u', 'p', 'i', 'n')

Como tupla é o nome de uma função interna, evite usá-la como nome de variável.

A maioria dos operadores de lista também funciona com tuplas. Por exemplo, o operador de colchetes indexa um elemento.

In [104]:
t[0]

'l'

E o operador de fatia seleciona um intervalo de elementos.

In [105]:
t[1:3]

('u', 'p')

O operador `+` concatena tuplas.

In [106]:
tuple('lup') + ('i', 'n')

('l', 'u', 'p', 'i', 'n')

E o operador `*` duplica uma tupla um determinado número de vezes.

In [107]:
tuple('spam') * 2 

('s', 'p', 'a', 'm', 's', 'p', 'a', 'm')

A função `sorted` funciona com tuplas, mas o resultado é uma lista, não uma tupla.

In [113]:
sorted(t)

['i', 'l', 'n', 'p', 'u']

A função `reversed` também funciona com tuplas.

In [114]:
reversed(t)

O resultado é um objeto `reversed`, que podemos converter em uma lista ou tupla.

In [115]:
tuple(reversed(t))

('n', 'i', 'p', 'u', 'l')

Com base nos exemplos até agora, pode parecer que tuplas são a mesma coisa que listas.

#### 6.2.2. Tuplas são Imutáveis

Se você tentar modificar uma tupla com o operador de colchetes, você receberá um `TypeError`.

In [116]:
t[0] = 'L'

TypeError: 'tuple' object does not support item assignment

E tuplas não têm nenhum dos métodos que modificam listas, como `append` e `remove`.

In [117]:
t.remove('l')

AttributeError: 'tuple' object has no attribute 'remove'

Um `'atributo'` é uma variável ou método associado a um objeto (veremos isso no decorrer deste módulo) – essa mensagem de erro significa que as tuplas não têm um método chamado `remove`.

Como as tuplas são imutáveis, elas podem ser usadas como chaves em um dicionário. Por exemplo, o dicionário a seguir contém duas tuplas como chaves que mapeiam para números inteiros.

In [118]:
d = {}
d[1, 2] = 3
d[3, 4] = 7

Podemos procurar uma tupla em um dicionário assim:

In [119]:
d[1, 2]

3

Ou se tivermos uma variável que se refere a uma tupla, podemos usá-la como uma chave.

In [120]:
t = (3, 4)
d[t]

7

Tuplas também podem aparecer como valores em um dicionário.

In [121]:
t = tuple('abc')
d = {'key': t}
d

{'key': ('a', 'b', 'c')}

#### 6.2.3. Atribução de Tuplas

Você pode colocar uma tupla de variáveis ​​no lado esquerdo de uma atribuição e uma tupla de valores no lado direito.

In [122]:
a, b = 1, 2

Os valores são atribuídos às variáveis ​​da esquerda para a direita – neste exemplo, `a` obtém o valor `1` e `b` obtém o valor `2`. Podemos exibir os resultados assim:

In [123]:
a, b

(1, 2)

De forma mais geral, se o lado esquerdo de uma atribuição for uma tupla, o lado direito pode ser qualquer tipo de sequência – string, lista ou tupla. Por exemplo, para dividir um endereço de e-mail em um nome de usuário e um domínio, você poderia escrever:

In [124]:
email = 'monty@python.org'
username, domain = email.split('@')

O valor de retorno de `split` é uma lista com dois elementos – o primeiro elemento é atribuído ao `username`, o segundo ao `domain`.

In [125]:
username, domain

('monty', 'python.org')

O número de variáveis ​​à esquerda e o número de valores à direita devem ser os mesmos – caso contrário, você obterá um `ValueError`.

In [126]:
a, b = 1, 2, 3

ValueError: too many values to unpack (expected 2)

A atribuição de tuplas é útil se você quiser trocar os valores de duas variáveis. Com atribuições convencionais, você precisa usar uma variável temporária, como esta:

In [129]:
temp = a
a = b
b = temp

Isso funciona, mas com a atribuição de tupla podemos fazer a mesma coisa sem uma variável temporária.

In [130]:
print(a, b)
a, b = b, a
print(a, b)

2 1
1 2


Isso funciona porque todas as expressões do lado direito são avaliadas antes de qualquer atribuição.

Também podemos usar a atribuição de tuplas em uma instrução `for`. Por exemplo, para percorrer os itens de um dicionário, podemos usar o método `items`.

In [131]:
d = {'um': 1, 'dois': 2}

for item in d.items():
    key, value = item
    print(key, '->', value)

um -> 1
dois -> 2


A cada repetição do loop, o `item` recebe uma tupla que contém uma chave e o valor correspondente.

Podemos escrever este loop de forma mais concisa, assim:

In [132]:
for key, value in d.items():
    print(key, '->', value)

um -> 1
dois -> 2


A cada vez que passa pelo loop, uma chave e o valor correspondente são atribuídos diretamente à `key` e ao `value`.

#### 6.2.4. Tuplas como Valores de Retorno

A rigor, uma função só pode retornar um valor, mas se o valor for uma tupla, o efeito é o mesmo que retornar vários valores. Por exemplo, se você quiser dividir dois números inteiros e calcular o quociente e o resto, é ineficiente calcular `x//y` e depois `x%y`. É melhor calcular os dois ao mesmo tempo.

A função interna `divmod` recebe dois argumentos e retorna uma tupla de dois valores, o quociente e o resto.

In [133]:
divmod(7, 3)

(2, 1)

Podemos usar a atribuição de tupla para armazenar os elementos da tupla em duas variáveis.

In [134]:
quociente, resto = divmod(7, 3)
quociente

2

In [135]:
resto

1

Aqui está um exemplo de uma função que retorna uma tupla.

In [136]:
def min_max(t):
    return min(t), max(t)

`max` e `min` são funções internas que encontram os maiores e menores elementos de uma sequência. `min_max` calcula ambos e retorna uma tupla de dois valores.

In [137]:
min_max([2, 4, 1, 3])

(1, 4)

#### 6.2.5. Empacotamento de Argumentos

Funções podem receber um número variável de argumentos. Um nome de parâmetro que começa com o operador `*` **agrupa** os argumentos em uma tupla. Por exemplo, a função a seguir recebe qualquer número de argumentos e calcula sua média aritmética – ou seja, a soma deles dividida pelo número de argumentos.

In [139]:
def mean(*args):
    return sum(args) / len(args)

O parâmetro pode ter o nome que você quiser, mas `args` é o nome convencional. Podemos chamar a função assim:

In [140]:
mean(1, 2, 3)

2.0

Se você tiver uma sequência de valores e quiser passá-los para uma função como múltiplos argumentos, pode usar o operador `*` para **desempacotar** a tupla. Por exemplo, `divmod` recebe exatamente dois argumentos – se você passar uma tupla como parâmetro, receberá um erro.

In [142]:
t = (7, 3)
divmod(t)

TypeError: divmod expected 2 arguments, got 1

Mesmo que a tupla contenha dois elementos, ela conta como um único argumento. Mas se você descompactar a tupla, ela será tratada como dois argumentos.

In [143]:
divmod(*t)

(2, 1)

Empacotar e desempacotar pode ser útil se você quiser adaptar o comportamento de uma função existente. Por exemplo, esta função recebe qualquer número de argumentos, remove o menor e o maior e calcula a média dos demais.

In [144]:
def trimmed_mean(*args):
    low, high = min_max(args)
    trimmed = list(args)
    trimmed.remove(low)
    trimmed.remove(high)
    return mean(*trimmed)

Primeiro, ele usa `min_max` para encontrar os elementos mais baixos e mais altos. Em seguida, converte `args` em uma lista para poder usar o método `remove`. Por fim, ele descompacta a lista para que os elementos sejam passados ​​para `mean` como argumentos separados, em vez de uma única lista.

Aqui está um exemplo que mostra o efeito.

In [145]:
mean(1, 2, 3, 10)

4.0

In [146]:
trimmed_mean(1, 2, 3, 10)

2.5

Esse tipo de média `'aparada'` é usado em alguns esportes com julgamento subjetivo – como mergulho e ginástica – para reduzir o efeito de um juiz cuja pontuação se desvia dos outros.

#### 6.2.6. Zip

Tuplas são úteis para percorrer os elementos de duas sequências e realizar operações nos elementos correspondentes. Por exemplo, suponha que dois times joguem uma série de sete partidas e registremos suas pontuações em duas listas, uma para cada time.

In [148]:
scores1 = [1, 2, 4, 5, 1, 5, 2]
scores2 = [5, 5, 2, 2, 5, 2, 3]

Vamos ver quantos jogos cada time venceu. Usaremos `zip`, uma função interna que recebe duas ou mais sequências e retorna um **objeto zip**, assim chamado porque emparelha os elementos das sequências como os dentes de um zíper.

In [149]:
zip(scores1, scores2)

Podemos usar o objeto zip para percorrer os valores nas sequências em pares.

In [150]:
for pair in zip(scores1, scores2):
     print(pair)

(1, 5)
(2, 5)
(4, 2)
(5, 2)
(1, 5)
(5, 2)
(2, 3)


A cada volta do loop, `pair` recebe uma tupla de pontuações. Assim, podemos atribuir as pontuações às variáveis ​​e contabilizar as vitórias do primeiro time, assim:

In [151]:
wins = 0
for team1, team2 in zip(scores1, scores2):
    if team1 > team2:
        wins += 1
        
wins

3

Infelizmente, o primeiro time venceu apenas três jogos e perdeu a série.

Se você tiver duas listas e quiser uma lista de pares, pode usar `zip` e `list`.

In [152]:
t = list(zip(scores1, scores2))
t

[(1, 5), (2, 5), (4, 2), (5, 2), (1, 5), (5, 2), (2, 3)]

O resultado é uma lista de tuplas, então podemos obter o resultado do último jogo assim:

In [153]:
t[-1]

(2, 3)

Se você tiver uma lista de chaves e uma lista de valores, poderá usar `zip` e `dict` para criar um dicionário. Por exemplo, veja como podemos criar um dicionário que mapeia cada letra para sua posição no alfabeto.

In [154]:
letras = 'abcdefghijklmnopqrstuvwxyz'
numeros = range(len(letras))
letras_map = dict(zip(letras, numeros))

Agora podemos procurar uma letra e obter seu índice no alfabeto.

In [155]:
letras_map['a'], letras_map['z']

(0, 25)

Neste mapeamento, o índice de `'a'` é `0` e o índice de `'z'` é `25`.

Se você precisar percorrer os elementos de uma sequência e seus índices, poderá usar a função interna `enumerate`.

In [156]:
enumerate('abc')

O resultado é um **objeto enumerado** que percorre uma sequência de pares, onde cada par contém um índice (começando em 0) e um elemento da sequência fornecida.

In [157]:
for index, element in enumerate('abc'):
    print(index, element)

0 a
1 b
2 c


### 6.4. Exercícios

In [ ]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

#### 6.4.1. Exercício

Duas palavras são anagramas se você puder reorganizar as letras de uma para formar a outra. Por exemplo, `tops` é um anagrama de `stop`.

Uma maneira de verificar se duas palavras são anagramas é ordenar as letras em ambas as palavras. Se as listas de letras ordenadas forem iguais, as palavras são anagramas.

Escreva uma função chamada `is_anagram` que recebe duas strings e retorna `True` se forem anagramas.

Usando sua função e a lista de palavras, encontre todos os anagramas de `takes`.

In [160]:
# escreva aqui sua resposta

def is_anagrama(str1, str2):
    srt1_new = sorted(str1)
    srt2_new = sorted(str2)
    return srt1_new == srt2_new

lista_palavras = ['stop', 'ufc', 'sekat']
for palavra in lista_palavras:
    print('takes', palavra, is_anagrama('takes', palavra))

takes stop False
takes ufc False
takes sekat True


#### 6.4.2. Exercício

O Python fornece uma função interna chamada `reversed` que recebe como argumento uma sequência de elementos – como uma lista ou string – e retorna um objeto `reversed` que contém os elementos em ordem inversa.

In [ ]:
reversed('parrot')

Se você quiser os elementos invertidos em uma lista, você pode usar a função `list`.

In [ ]:
list(reversed('parrot'))

Ou se você quiser que eles fiquem em uma string, você pode usar o método `join`.

In [ ]:
''.join(reversed('parrot'))

Então podemos escrever uma função que inverte uma palavra como esta.

In [ ]:
def reverse_word(word):
    return ''.join(reversed(word))

Um palíndromo é uma palavra que se escreve da mesma forma, de trás para frente, como `"noon"` e `"rotator"`. Escreva uma função chamada `is_palindrome` que receba um argumento string e retorne `True` se for um palíndromo e `False` caso contrário.

Você pode usar o seguinte loop para encontrar todos os palíndromos na lista de palavras com pelo menos 5 letras.

```python
word_list = ['universidade', 'arara', 'racecar', 'reviver', 
             'araraquara', 'campeão', 'televisão']
for word in word_list:
    if len(word) >= 5 and is_palindrome(word):
        print(word)
```

In [ ]:
# escreva aqui sua resposta

#### 6.4.3. Exercício

Escreva uma função chamada `reverse_sentence` que receba como argumento uma string contendo qualquer número de palavras separadas por espaços. Ela deve retornar uma nova string contendo as mesmas palavras em ordem inversa. Por exemplo, se o argumento for "Reverter esta frase", o resultado deverá ser "Frase esta reverter".

**Dica**: Você pode usar os métodos de string para colocar a primeira palavra em maiúscula e converter as demais para minúsculas.

In [ ]:
# escreva aqui sua resposta

#### 6.4.4. Exercício

Escreva uma função chamada `total_length` que recebe uma lista de strings e retorna o comprimento total das strings.

In [ ]:
# escreva aqui sua resposta

#### 6.4.5. Exercício

Os dicionários têm um método chamado `get` que recebe uma chave e um valor padrão. Se a chave aparecer no dicionário, `get` retorna o valor correspondente; caso contrário, retorna o valor padrão. Por exemplo, aqui está um dicionário que mapeia as letras em uma string para o número de vezes que elas aparecem.

In [ ]:
counter = value_counts('brontosaurus')

Se procurarmos uma letra que aparece na palavra, `get` retorna o número de vezes que ela aparece.

In [ ]:
counter.get('b', 0)

Se procurarmos uma letra que não aparece, obtemos o valor padrão, `0`.

In [ ]:
counter.get('c', 0)

Use `get` para escrever uma versão mais concisa de value_counts. Você deve conseguir eliminar a instrução `if`.

In [ ]:
# escreva aqui sua resposta

#### 6.4.6. Exercício

Qual é a palavra mais longa que você consegue imaginar, onde cada letra aparece apenas uma vez? Vamos ver se conseguimos encontrar uma mais longa do que `'configurável'`.

Escreva uma função chamada `has_duplicates` que recebe uma sequência – como uma lista ou string – como parâmetro e retorna `True` se houver algum elemento que apareça na sequência mais de uma vez.

In [ ]:
# escreva aqui sua resposta

#### 6.4.7. Exercício

Escreva uma função chamada `find_repeats` que recebe um dicionário que mapeia cada chave para um contador, como o resultado de `value_counts`. Ela deve percorrer o dicionário e retornar uma lista de chaves com contagens maiores que `1`. Você pode usar o seguinte esquema para começar.

```python
def find_repeats(counter):
    """Cria uma lista de chaves com valores maiores que 1.

    counter: dicionário que mapeia de chaves para contagens

    returns: lista de chaves
    """
    return []
```

In [ ]:
# escreva aqui sua resposta

#### 6.4.8. Exercício

Suponha que você execute `value_counts` com duas palavras diferentes e salve os resultados em dois dicionários.

```python
counter1 = value_counts('brontosaurus')
counter2 = value_counts('apatosaurus')
```

Cada dicionário mapeia um conjunto de letras para o número de vezes que elas aparecem. Escreva uma função chamada `add_counters` que recebe dois dicionários como estes e retorna um novo dicionário contendo todas as letras e o número total de vezes que elas aparecem em cada palavra.

In [ ]:
# escreva aqui sua resposta

#### 6.4.9. Exercício

Nesta seção, eu disse que tuplas podem ser usadas como chaves em dicionários porque são hasháveis, e são hasháveis ​​porque são imutáveis. Mas isso nem sempre é verdade.

Se uma tupla contém um valor mutável, como uma lista ou um dicionário, a tupla não é mais hashável porque contém elementos que não são hasháveis. Como exemplo, aqui está uma tupla que contém duas listas de inteiros.

In [ ]:
list0 = [1, 2, 3]
list1 = [4, 5]

t = (list0, list1)
t

Escreva uma linha de código que anexe o valor `6` ao final da segunda lista em `t`. Se você exibir `t`, o resultado deverá ser `([1, 2, 3], [4, 5, 6])`.

In [ ]:
# escreva aqui sua resposta

Tente criar um dicionário que mapeie de `t` para uma string e confirme se você obtém um `TypeError`.

```python
d = {t: 'this tuple contains two lists'}
```

In [ ]:
# escreva aqui sua resposta

#### 6.4.10. Exercício

Considere um dicionário que mapeia cada letra até seu índice no alfabeto.

```python
letters = 'abcdefghijklmnopqrstuvwxyz'
numbers = range(len(letters))
letter_map = dict(zip(letters, numbers))
```

Por exemplo, o índice de `'a'` é `0`.

```python
letter_map['a']

0
```

Para ir na outra direção, podemos usar a indexação de lista. Por exemplo, a letra no índice `1` é `'b'`.

```python
letters[1]

'b'
```

Podemos usar `letter_map` e `letters` para codificar e decodificar palavras usando uma *cifra de César*.

Uma cifra de César é uma forma fraca de criptografia que envolve deslocar cada letra por um número fixo de casas no alfabeto, retornando ao início, se necessário. Por exemplo, `'a'` deslocado em 2 casas é `'c'` e `'z'` deslocado em 1 casa é `'a'`.

Escreva uma função chamada `shift_word` que recebe como parâmetros uma string e um inteiro e retorna uma nova string contendo as letras da string deslocadas pelo número de casas fornecido.

Para testar sua função, confirme que `"cheer"` deslocado em `7` casas é `"jolly"` e `"melon"` deslocado em `16` casas é `"cubed"`.

**Dicas**: Use o operador de módulo para retornar de `'z'` para `'a'`. Faça um loop pelas letras da palavra, desloque cada uma delas e anexe o resultado a uma lista de letras. Em seguida, use `join` para concatenar as letras em uma string.

In [169]:
# escreva aqui sua resposta
letters = 'abcdefghijklmnopqrstuvwxyz'
numbers = range(len(letters))
letter_map = dict(zip(letters, numbers))

def shift_word(word, shift):
    encrypted_word = []
    for c in word:
        new_index = (letter_map[c] + shift) % len(letters)
        encrypted_word.append(letters[new_index])
    
    return ''.join(encrypted_word)

print(shift_word('cheer', 7))
print(shift_word('melon', 16))

texto = "ola mundo cruel"

c = []
for palavra in texto.split():
    c.append(shift_word(palavra, 3))

print(' '.join(c))

jolly
cubed
rod pxqgr fuxho


#### 6.4.11. Exercício

Escreva uma função chamada `word_distance` que recebe duas palavras com o mesmo comprimento e retorna o número de casas onde as duas palavras diferem.

**Dica**: Use `zip` para percorrer as letras correspondentes das palavras.

In [173]:
# escreva aqui sua resposta

def word_distance(palavra_1, palavra_2):
    count = 0
    for c_1, c_2 in zip(palavra_1, palavra_2):
        if c_1 != c_2:
            count += 1
    return count

print(word_distance("abacate", "laranja"))
print(word_distance("abacate", "abaxage"))

7
2


## 7. Módulos e Pacotes

Nessa seção iremos abordar o conceito de modularidade em Python em termos de módulo, bibliotecas e orientação a objetos.

### 7.1. Scripts como Módulo

Ao sair e entrar de novo no interpretador Python, as definições anteriores (funções e variáveis) são perdidas. Portanto, se quiser escrever um programa maior, será mais eficiente usar um editor de texto para preparar as entradas para o interpretador, e executá-lo usando o arquivo como entrada. Isso é conhecido como criar um *script*. Se o programa se torna ainda maior, é uma boa prática dividi-lo em arquivos menores, para facilitar a manutenção. Também é preferível usar um arquivo separado para uma função que você escreveria em vários programas diferentes, para não copiar a definição de função em cada um deles.

Para permitir isso, Python tem uma maneira de colocar as definições em um arquivo e então usá-las em um script ou em uma execução interativa do interpretador. Tal arquivo é chamado de *módulo*; definições de um módulo podem ser importadas para outros módulos, ou para o módulo *principal* (a coleção de variáveis a que você tem acesso num script executado como um programa).

Um módulo é um arquivo contendo definições e instruções Python. O nome do arquivo é o nome do módulo acrescido do sufixo `.py`. Dentro de um módulo, o nome do módulo (como uma string) está disponível como o valor da variável global `__name__`. Por exemplo, use seu editor de texto favorito para criar um arquivo chamado `fibo.py` no diretório atual com o seguinte conteúdo:

```python
# Módulo de números de Fibonacci

def fib_print(n):
    """Escreve a série de Fibonacci até n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

def fib_build(n):
    """Retorna a série de Fibonacci até n."""
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result
```

Agora, e importe esse módulo com o seguinte comando:

In [174]:
import fibo

Isso adiciona o nome do módulo `fibo.py` no espaço de nomes do programa principal. Assim, usando o nome do módulo, você pode acessar as funções:

In [175]:
fibo.fib_print(100)

0 1 1 2 3 5 8 13 21 34 55 89 


In [176]:
fibo.fib_build(100)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

### 7.2. Mais sobre Módulos

Um módulo pode conter tanto instruções executáveis quanto definições de funções e classes. Essas instruções servem para inicializar o módulo. Eles são executados somente na *primeira* vez que o módulo é encontrado em uma instrução de importação. (Também rodam se o arquivo é executado como um *script*.)

Cada módulo tem seu próprio espaço de nomes privado, que é usado como espaço de nomes global para todas as funções definidas no módulo. Assim, o autor de um módulo pode usar variáveis globais no seu módulo sem se preocupar com conflitos acidentais com as variáveis globais do usuário. Por outro lado, se você precisar usar uma variável global de um módulo, poderá fazê-lo com a mesma notação usada para se referir às suas funções, `nomemodulo.nomeitem`.

Módulos podem importar outros módulos. É costume, porém não obrigatório, colocar todas as instruções import no início do módulo (ou script , se preferir). As definições do módulo importado, se colocados no nível de um módulo (fora de quaisquer funções ou classes), elas são adicionadas a espaço de nomes global da módulo.

Existe uma variante da instrução `import` que importa definições de um módulo diretamente para o espaço de nomes do módulo importador. Por exemplo:

In [177]:
from fibo import fib_build, fib_print

fib_print(100)
fib_build(100)

0 1 1 2 3 5 8 13 21 34 55 89 


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

Isso não coloca o nome do módulo de onde foram feitas as importações no espaço de nomes local (assim, no exemplo, `fibo` não está definido).

Existe ainda uma variante que importa todos os nomes definidos em um módulo:

In [178]:
from fibo import *

fib_print(100)

0 1 1 2 3 5 8 13 21 34 55 89 


Isso importa todos as declarações de nomes, exceto aqueles que iniciam com um sublinhado (`_`). Na maioria dos casos, programadores Python não usam esta facilidade porque ela introduz um conjunto desconhecido de nomes no ambiente, podendo esconder outros nomes previamente definidos.

Note que, em geral, a prática do `import *` de um módulo ou pacote é desaprovada, uma vez que muitas vezes dificulta a leitura do código. Contudo, é aceitável para diminuir a digitação em sessões interativas.

Se o nome do módulo é seguido pela palavra-chave `as`, o nome a seguir é vinculado diretamente ao módulo importado.

In [179]:
import fibo as fib

fib.fib_print(100)

0 1 1 2 3 5 8 13 21 34 55 89 


Isto efetivamente importa o módulo, da mesma maneira que `import fibo` fará, com a única diferença de estar disponível com o nome `fib`(como um *alias*).

Também pode ser utilizado com a palavra-chave `from`, com efeitos similares:

In [180]:
from fibo import fib_print as fibonacci

fibonacci(100)

0 1 1 2 3 5 8 13 21 34 55 89 


> Por motivos de eficiência, cada módulo é importado apenas uma vez por sessão do interpretador. Portanto, se você alterar seus módulos, deverá reiniciar o interpretador.

### 7.3. Pacotes

Os pacotes são uma maneira de estruturar o `"espaço de nomes"` dos módulos Python, usando `"nomes de módulo com pontos"`. Por exemplo, o nome do módulo `A.B` designa um submódulo chamado `B`, em um pacote chamado `A`. Assim como o uso de módulos evita que os autores de módulos diferentes tenham que se preocupar com nomes de variáveis globais, o uso de nomes de módulos com pontos evita que os autores de pacotes com muitos módulos, como `NumPy` ou `Pandas`, tenham que se preocupar com os nomes dos módulos uns dos outros.

Suponha que você queira projetar uma coleção de módulos (um `"pacote"`) para o gerenciamento uniforme de arquivos de som. Existem muitos formatos diferentes (normalmente identificados pela extensão do nome de arquivo, por exemplo `.wav`, `.aiff`, `.au`), de forma que você pode precisar criar e manter uma crescente coleção de módulos de conversão entre formatos. Ainda podem existir muitas operações diferentes, passíveis de aplicação sobre os arquivos de som (mixagem, eco, equalização, efeito stereo artificial). Logo, possivelmente você também estará escrevendo uma coleção sempre crescente de módulos para aplicar estas operações. Eis uma possível estrutura para o seu pacote (expressa em termos de um sistema de arquivos hierárquico):

```python
sound/                          Pacote de nível superior
      __init__.py               Inicializa o pacote de som
      formats/                  Subpacote para as conversões entre formatos de arquivos
              __init__.py
              wavread.py
              wavwrite.py
              aiffread.py
              aiffwrite.py
              auread.py
              auwrite.py
              ...
      effects/                  Subpacote para efeitos de som
              __init__.py
              echo.py
              surround.py
              reverse.py
              ...
      filters/                  Subpacote para filtros
              __init__.py
              equalizer.py
              vocoder.py
              karaoke.py
              ...
```

Os arquivos `__init__.py` são necessários para que o Python trate diretórios contendo o arquivo como pacotes (a menos que se esteja usando um pacote de espaço de nomes, um recurso relativamente avançado). Isso impede que diretórios com um nome comum, como string, ocultem, involuntariamente, módulos válidos que ocorrem posteriormente no caminho de busca do módulo. No caso mais simples, `__init__.py` pode ser apenas um arquivo vazio, mas pode também executar código de inicialização do pacote, ou configurar a variável `__all__`, descrita mais adiante.

Usuários do pacote podem importar módulos individuais, por exemplo:

```python
import sound.effects.echo
```

Isso carrega o submódulo `sound.effects.echo`. Ele deve ser referenciado com seu nome completo, como em:

```python
sound.effects.echo.echofilter(input, output, delay=0.7, atten=4)
```

Uma maneira alternativa para a importação desse módulo é:

```python
from sound.effects import echo
```

Isso carrega o submódulo echo sem necessidade de mencionar o prefixo do pacote no momento da utilização, assim:

```python
echo.echofilter(input, output, delay=0.7, atten=4)
```

Também é possível importar diretamente uma única variável ou função:

```python
from sound.effects.echo import echofilter
```

Novamente, isso carrega o submódulo echo, mas a função `echofilter()` está acessível diretamente sem prefixo:

```python
echofilter(input, output, delay=0.7, atten=4)
```

Observe que ao utilizar `from pacote import item`, o `item` pode ser um subpacote, submódulo, classe, função ou variável. A instrução `import` primeiro testa se o `item` está definido no pacote, senão presume que é um módulo e tenta carregá-lo. Se falhar em encontrar o módulo, uma exceção `ImportError` é levantada.

Em oposição, em uma construção como `import item.subitem.subsubitem`, cada item, com exceção do último, deve ser um pacote. O último pode ser também um pacote ou módulo, mas nunca uma classe, função ou variável contida em um módulo.

### 7.4. Importando * de um Pacote

Agora, o que acontece quando um usuário escreve `from sound.effects import *`? Idealmente, poderia se esperar que este comando vasculhasse o sistema de arquivos, encontrasse todos os submódulos presentes no pacote, e os importasse. Isso poderia demorar muito e a importação de submódulos pode ocasionar efeitos colaterais, que somente deveriam ocorrer quando o submódulo é explicitamente importado.

A única solução é o autor do pacote fornecer um índice explícito do pacote. A instrução `import` usa a seguinte convenção: se o arquivo `__init__.py` do pacote define uma lista chamada `__all__`, então esta lista indica os nomes dos módulos a serem importados quando a instrução `from pacote import *` é acionada. Fica a cargo do autor do pacote manter esta lista atualizada, inclusive fica a seu critério excluir inteiramente o suporte a importação direta de todo o pacote através de from pacote `import *`. Por exemplo, o arquivo `sounds/effects/__init__.py` poderia conter apenas:

```python
__all__ = ["echo", "surround", "reverse"]
```

Isso significaria que `from sound.effects import *` importaria os três submódulos nomeados do pacote `sound.effects`.

Esteja ciente de que os submódulos podem ficar sobrepostos por nomes definidos localmente. Por exemplo, se você adicionou uma função `reverse` ao arquivo `sound/effects/__init__.py`, usar `from sound.effects import *` só importaria os dois submódulos `echo e surround`, mas não o submódulo `reverse`, porque ele fica sobreposto pela função `reverse` definida localmente:

```python
__all__ = [
    "echo",      # refere-se ao arquivo 'echo.py'
    "surround",  # refere-se ao arquivo 'surround.py'
    "reverse",   # !!! refere-se à função 'reverse' agora !!!
]

def reverse(msg: str):  # <-- este nome ofusca o submódulo 'reverse.py'
    return msg[::-1]    #     no caso de uma importação 'from sound.effects import *'
```

Se `__all__` não estiver definido, a instrução `from sound.effects import *` não importa todos os submódulos do pacote `sound.effects` no espaço de nomes atual. Há apenas garantia que o pacote `sound.effects` foi importado (possivelmente executando qualquer código de inicialização em `__init__.py`) juntamente com os nomes definidos no pacote. Isso inclui todo nome definido em `__init__.py` bem como em qualquer submódulo importado a partir deste. Também inclui quaisquer submódulos do pacote que tenham sido carregados explicitamente por instruções `import` anteriores. Considere o código abaixo:

```python
import sound.effects.echo
import sound.effects.surround
from sound.effects import *
```

Nesse exemplo, os módulos `echo` e `surround` são importados no espaço de nomes atual, no momento em que a instrução `from...import` é executada, pois estão definidos no pacote `sound.effects`. (Isso também funciona quando `__all__` estiver definida.)

Apesar de que certos módulos são projetados para exportar apenas nomes conforme algum critério quando se faz `import *`, ainda assim essa sintaxe é considerada uma prática ruim em código de produção.

Lembre-se, não há nada errado em usar `from pacote import submodulo_especifico`! De fato, essa é a notação recomendada, a menos que o módulo importado necessite usar submódulos com o mesmo nome, de diferentes pacotes.

### 7.5. Biblioteca de Funções

Uma biblioteca de funções é um conjunto de rotinas ou procedimentos pré-definidos que podem ser chamados e reutilizados em um programa de computador. Um programa pode utilizar recursos de uma biblioteca a fim de contribuir para alcançar seu objetivo.

Em Python, podemos usar o conceito de módulos para criar bibliotécas. Um módulo pode conter quaisquer recursos e estruturas do Python: Variáveis, Funções e Classes. Por exemplo, considere a seguinte estrutura do pacote `matematica`:

```python
matematica/                          Pacote de nível superior
           __init__.py               Inicializa o pacote de matematica
           calculadora.py
```

O arquivo `__init__.py` contém o seguinte conteúdo:

```python
__all__ = [
    "calculadora"      # refere-se ao arquivo 'calculadora.py'
]
```

O arquivo `calculadora.py` contém o seguinte conteúdo:

```python
def sum(a, b):
    return a + b

def sub(a, b):
    return a - b

def mut(a, b):
    return a * b

def div(a, b):
    return a / b
```

O pacote `matematica` disponibiliza o módulo `calculadora` que funciona como uma bibliotéca de funções (uma vez que seu conteúdo e constituído apenas de funções). Assim, podemos reutilizar as funções definidas em `calculadora.py` através de um processo de importação da seguinte forma:

In [181]:
from matematica import calculadora

print(calculadora.sum(10,12))
print(calculadora.sub(51,21))
print(calculadora.mut(11,10))
print(calculadora.div(20,10))

22
30
110
2.0


Podemos ainda dar uma **alias** para a bliblioteca a fim de melhorar a legibilidade ou evitar sobreposição de nomes de variáveis no programa:

In [182]:
from matematica import calculadora as calc

print(calc.sum(10,12))
print(calc.sub(51,21))
print(calc.mut(11,10))
print(calc.div(20,10))

22
30
110
2.0


Podemos ainda fazer a importação de outra forma:

In [3]:
from matematica.calculadora import *

print(sum(10,12))
print(sub(51,21))
print(mut(11,10))
print(div(20,10))

22
30
110
2.0


Nesse caso, fazemos o `import` de todas as funções de `calculadora`. Eventualmente, poderíamos importar apenas as funções desejadas:

In [4]:
from matematica.calculadora import sum, sub

print(sum(10,12))
print(sub(51,21))

22
30


Observe que, nesse caso, se fizermos chamadas às demais funções, ocorrerá um erro do tipo `NameError`:

In [5]:
print(mut(11,10))
print(div(20,10))

110
2.0


### 7.6. Exercícios

In [ ]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

#### 7.6.1. Exercício

Utilizando o conceito de módulos e pacotes do Python, desenvolva o seguinte pacote:

```python
matematica/                          Pacote de nível superior
           __init__.py               Inicializa o pacote de matematica
           aritmetica.py
           geometria.py
```

O arquivo `__init__.py` deve conter o seguinte conteúdo:

```python
__all__ = [
    "aritmetica",      # refere-se ao arquivo 'aritmetica.py'
    "geometria",       # refere-se ao arquivo 'geometria.py'
]
```

O arquivo `aritmetica.py` deve conter o seguinte conteúdo:

```python
def sum(a, b):
    return a + b

def sub(a, b):
    return a - b

def mut(a, b):
    return a * b

def div(a, b):
    return a / b
```

O arquivo `geometria.py` deve conter o seguinte conteúdo:

```python
import math

def area_retangulo(base, altura):
    return base * altura

def area_circulo(raio):
    return math.pi * raio**2

def area_triangulo(base, altura):
    return (base * altura) / 2

def volume_efera(raio):
    return 4/3 * math.pi * raio**3
```

Depois de implementado, importe e execute as funções os módulos.

In [ ]:
from matematica import aritmetica, geometria

print(aritmetica.sum(10,12))
print(aritmetica.sub(51,21))
print(aritmetica.mut(11,10))
print(aritmetica.div(20,10))

print(geometria.area_retangulo(20,15))
print(geometria.area_circulo(15))
print(geometria.area_triangulo(20,15))
print(geometria.volume_efera(15))

#### 7.6.2. Exercício

Estenda o exercício anterior para adicionar o módulo `algebra`:

```python
matematica/                          Pacote de nível superior
           __init__.py               Inicializa o pacote de matematica
           aritmetica.py
           geometria.py
           algebra.py                Novo módulo         
```

O arquivo `__init__.py` deve conter o seguinte conteúdo:

```python
__all__ = [
    "aritmetica",      # refere-se ao arquivo 'aritmetica.py'
    "geometria",       # refere-se ao arquivo 'geometria.py'
    "algebra",         # refere-se ao arquivo 'algebra.py'    
]
```

O arquivo `algebra.py` deve conter o seguinte conteúdo:

```python
import math

def calcular_delta(a, b, c):
    return b ** 2 - 4 * a * c

def calcular_raizes(a, b, c):
    delta = calcular_delta()
    if delta < 0:
        return None  # não existem raízes reais
    elif delta == 0:
        x = -b / (2 * a)
        return (x, x)
    else:
        x1 = (-b + math.sqrt(delta)) / (2 * a)
        x2 = (-b - math.sqrt(delta)) / (2 * a)
        return (x1, x2)
```

In [ ]:
from matematica import aritmetica, geometria, algebra

print(aritmetica.sum(10,12))
print(aritmetica.sub(51,21))
print(aritmetica.mut(11,10))
print(aritmetica.div(20,10))

print(geometria.area_retangulo(20,15))
print(geometria.area_circulo(15))
print(geometria.area_triangulo(20,15))
print(geometria.volume_efera(15))

print(algebra.calcular_raizes(1.0, -3.0, 2.0))
print(algebra.calcular_raizes(1.0, 2.0, 5.0))
print(algebra.calcular_raizes(1.0, 4.0, 4.0))

## 8. Orientação a Objetos

A programação orientada a objetos (POO) em Python ajuda você a estruturar seu código agrupando dados e comportamentos relacionados em **objetos**. Você começa definindo **classes**, que funcionam como modelos, e então cria objetos a partir delas. A POO simplifica a modelagem de conceitos do mundo real em seus programas e permite que você construa sistemas mais reutilizáveis ​​e escaláveis.

Nesta seção, exploraremos como definir classes, instanciar classes para criar objetos e aproveitar a herança para construir sistemas robustos em Python.

### 8.1. O que é Programação Orientada a Objetos?


A programação orientada a objetos é um paradigma de programação que fornece um meio de estruturar programas de forma que propriedades e comportamentos sejam agrupados em **objetos** individuais.

Por exemplo, um objeto pode representar uma pessoa com **propriedades** como nome, idade e endereço, e **comportamentos** como andar, falar, respirar e correr. Ou pode representar um e-mail com propriedades como lista de destinatários, assunto e corpo, e comportamentos como adicionar anexos e enviar.

Em outras palavras, a programação orientada a objetos é uma abordagem para modelar coisas concretas do mundo real, como carros, bem como relações entre coisas, como empresas e funcionários ou alunos e professores. A POO modela entidades do mundo real como objetos de software que possuem alguns dados associados a eles e podem executar determinadas operações.

A POO também existe em outras linguagens de programação e é frequentemente descrita como centrada nos quatro pilares, ou quatro princípios da POO:

- O **encapsulamento** permite agrupar dados (atributos) e comportamentos (métodos) dentro de uma classe para criar uma unidade coesa. Ao definir métodos para controlar o acesso a atributos e sua modificação, o encapsulamento ajuda a manter a integridade dos dados e promove um código modular e seguro.

- A **herança** permite a criação de relacionamentos hierárquicos entre classes, permitindo que uma subclasse herde atributos e métodos de uma classe pai. Isso promove a reutilização de código e reduz a duplicação.

- A **abstração** se concentra em ocultar detalhes de implementação e expor apenas a funcionalidade essencial de um objeto. Ao impor uma interface consistente, a abstração simplifica as interações com objetos, permitindo que os desenvolvedores se concentrem no que um objeto faz, em vez de como ele atinge sua funcionalidade.

- O **polimorfismo** permite tratar objetos de diferentes tipos como instâncias do mesmo tipo base, desde que implementem uma interface ou comportamento comum. A tipagem duck do Python o torna especialmente adequado para polimorfismo, pois permite acessar atributos e métodos em objetos sem precisar se preocupar com sua classe real.

Esta seção, você adotará uma abordagem prática para entender a POO em Python. Mas manter esses quatro conceitos de programação orientada a objetos em mente pode ajudá-lo a se lembrar das informações coletadas.

A principal conclusão é que os objetos estão no centro da programação orientada a objetos em Python. Em outros paradigmas de programação, os objetos representam apenas os dados. Em POO, eles também informam a estrutura geral do programa.

### 8.2. Como definir uma classe?

Em Python, você define uma classe usando a palavra-chave `class` seguida de um nome e dois pontos (`:`). Em seguida, você usa `.__init__()` para declarar quais atributos cada instância da classe deve ter:

In [ ]:
class Employee:
    def __init__(self, name, age):
        self.name =  name
        self.age = age

Mas o que tudo isso significa? E por que você precisa de classes, para começo de conversa? Dê um passo para trás e considere usar estruturas de dados primitivas integradas como alternativa.

Estruturas de dados primitivas — como números, strings e listas — são projetadas para representar informações simples, como o preço de uma maçã, o nome de um poema ou suas cores favoritas, respectivamente. E se você quiser representar algo mais complexo?

Por exemplo, você pode querer rastrear funcionários em uma organização. Você precisa armazenar algumas informações básicas sobre cada funcionário, como nome, idade, cargo e ano em que começou a trabalhar.

Uma maneira de fazer isso é representar cada funcionário como uma lista:

In [ ]:
kirk = ["James Kirk", 34, "Captain", 2265]
spock = ["Spock", 35, "Science Officer", 2254]
mccoy = ["Leonard McCoy", "Chief Medical Officer", 2266]

Há vários problemas com essa abordagem.

Primeiro, ela pode dificultar o gerenciamento de arquivos de código maiores. Se você referenciar `kirk` várias linhas depois de onde declarou a lista `kirk`, lembrará que o elemento com índice `0` é o `nome` do funcionário?

Segundo, ela pode introduzir erros se os funcionários não tiverem o mesmo número de elementos em suas respectivas listas. Na lista `mccoy` acima, a idade está ausente, então `mccoy` retornará `"Chief Medical Officer"` em vez da idade do Dr. McCoy.

Uma ótima maneira de tornar esse tipo de código mais gerenciável e de fácil manutenção é usar classes.

### 8.3. Classes vs Instâncias

Classes permitem criar estruturas de dados definidas pelo usuário. Classes definem funções especiais chamadas **métodos**, que identificam os comportamentos e ações que um objeto criado a partir da classe pode executar com seus dados.

Nesta seção, usaremos uma classe `Dog` que armazena algumas informações sobre as características e comportamentos que um cachorro pode ter.

Uma classe é um modelo de como definir algo. Na verdade, ela não contém nenhum dado. A classe `Dog` especifica que um nome e uma idade são necessários para definir um cachorro, mas não contém o nome ou a idade de nenhum cachorro específico.

Enquanto a classe é o modelo, uma **instância** é um objeto construído a partir de uma classe e contém dados reais. Uma instância da classe `Dog` não é mais um modelo. É um cachorro de verdade com um nome, como `'Miles'`, que tem quatro anos.

Em outras palavras, uma classe é como um formulário ou questionário. Uma instância é como um formulário que você preencheu com informações. Assim como muitas pessoas podem preencher o mesmo formulário com suas próprias informações exclusivas, você pode criar muitas instâncias de uma única classe.

### 8.4. Definição de Classe

Inicie todas as definições de classe com a palavra-chave `class` e, em seguida, adicione o nome da classe e dois pontos (`:`). O Python considerará qualquer código que você recuar abaixo da definição da classe como parte do corpo da classe.

Aqui está um exemplo da classe `Dog`:

In [1]:
class Dog:
    pass

O corpo da classe `Dog` consiste em uma única instrução: a palavra-chave `pass`. Programadores Python costumam usar pass como um espaço reservado para indicar onde o código será inserido. Isso permite que você execute esse código sem que o Python gere um erro.

A classe `Dog` não é muito interessante agora, vamos incrementá-la um pouco definindo algumas propriedades que todos os objetos `Dog` devem ter. Há várias propriedades que você pode escolher, incluindo nome, idade, cor da pelagem e raça. Para manter o escopo do exemplo pequeno, usaremos apenas nome e idade.

Definimos as propriedades que todos os objetos `Dog` devem ter em um método chamado `.__init__()`. Toda vez que você cria um novo objeto `Dog`, `.__init__()` define o **estado inicial** do objeto atribuindo os valores das propriedades do objeto. Ou seja, `.__init__()` inicializa cada nova instância da classe.

Podemos atribuir a `.__init__()` qualquer número de parâmetros, mas o primeiro parâmetro sempre será uma variável chamada `self`. Ao criar uma nova instância de classe, o Python passa automaticamente a instância para o parâmetro `self` em `.__init__()` para que o Python possa definir os novos atributos no objeto.

Vamos atualizar a classe `Dog` com um método `.__init__()` que cria atributos `.name` e `.age`:

In [2]:
class Dog:
    def __init__(self, name, age):
        self.name = name
        self.age = age

Precisamos nos certificar de recuar a assinatura do método `.__init__()` em quatro espaços e o corpo do método em oito espaços. Esse recuo é de vital importância. Ele informa ao Python que o método .`__init__()` pertence à classe `Dog`.

No corpo de `.__init__()`, há duas instruções usando a variável `self`:

- `self.name = name` cria um atributo chamado `name` e atribui a ele o valor do parâmetro `name`.
- `self.age = age` cria um atributo chamado `age` e atribui a ele o valor do parâmetro `age`.

Atributos criados em `.__init__()` são chamados de atributos de instância. O valor de um atributo de instância é específico para uma instância específica da classe. Todos os objetos `Dog` têm um nome e uma idade, mas os valores dos atributos `name` e `age` variam dependendo da instância `Dog`.

Por outro lado, atributos de classe são atributos que têm o mesmo valor para todas as instâncias de classe. Você pode definir um atributo de classe atribuindo um valor a um nome de variável fora de `.__init__()`.

Por exemplo, a classe `Dog` a seguir tem um atributo de classe chamado `species` com o valor `"Canis familiaris"`:

In [3]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

Defina os atributos de classe diretamente abaixo da primeira linha do nome da classe e os indentie com quatro espaços. Você sempre precisa atribuir um valor inicial a eles. Ao criar uma instância da classe, o Python cria e atribui automaticamente atributos de classe aos seus valores iniciais.

Use atributos de classe para definir propriedades que devem ter o mesmo valor para todas as instâncias da classe. Use atributos de instância para propriedades que variam de uma instância para outra.

Agora que você temos uma classe `Dog`, é hora de criar alguns cachorros!

### 8.5. Criando Instâncias

Criar um novo objeto a partir de uma classe é chamado de **instanciação de classe**. Você pode criar um novo objeto digitando o nome da classe, seguido de abrir e fechar parênteses:

In [4]:
class Dog:
    pass

Dog()

Primeiro, criamos uma nova classe `Dog` sem atributos ou métodos e, em seguida, instanciamos a classe `Dog` para criar um objeto.

Na saída acima, você pode ver que agora tem um novo objeto Dog em `0x106d76c50`. Essa sequência estranha de letras e números é um endereço de memória que indica onde o Python armazena o objeto da classe Dog na memória do seu computador. Observe que o endereço na tela será diferente.

Agora, ao instancia a classe Dog uma segunda vez para criar outro objeto:

In [5]:
Dog()

A nova instância de `Dog` está localizada em um endereço de memória diferente. Isso ocorre porque é uma instância inteiramente nova e completamente diferente do primeiro objeto `Dog` que foi criado.

Para ver isso de outra forma:

In [6]:
a = Dog()
b = Dog()
a == b

False

Neste código, você cria dois novos objetos `Dog` e os atribui às variáveis `​a` e `b`. Ao comparar `a` e `b` usando o operador `==`, o resultado é `False`. Embora `a` e `b` sejam instâncias da classe `Dog`, eles representam dois objetos distintos na memória.

### 8.6. Classes e Atributos de Instância

Criando uma nova classe `Dog` com um atributo de classe chamado `.species` e dois atributos de instância chamados `.name` e `.age`:

In [7]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

Para instanciar esta classe `Dog`, precisamos fornecer valores para `name` e `age`. Caso contrário, o Python gerará um `TypeError`:

In [8]:
Dog()

TypeError: Dog.__init__() missing 2 required positional arguments: 'name' and 'age'

Para passar argumentos para os parâmetros `name` e `age`, devemos colocar os valores entre parênteses após o nome da classe:

In [9]:
miles = Dog("Miles", 4)
buddy = Dog("Buddy", 9)

Isso cria duas novas instâncias de `Dog` — uma para um cachorro de quatro anos chamado `Miles` e outra para um cachorro de nove anos chamado `Buddy`.

O método `.__init__()` da classe Dog tem três parâmetros, então por que você está passando apenas dois argumentos para ele no exemplo?

Ao instanciar a classe `Dog`, o Python cria uma nova instância de `Dog` e a passa para o primeiro parâmetro de `.__init__()`. Isso essencialmente remove o parâmetro `self`, então você só precisa se preocupar com os parâmetros `name` e `age`.

Depois de criar as instâncias de `Dog`, podemos acessar seus atributos de instância usando a notação de ponto:

In [10]:
print(miles.name, miles.age)
print(buddy.name, buddy.age)

Miles 4
Buddy 9


Podemos acessar atributos de classe da mesma maneira:

In [12]:
print(buddy.species)

Canis familiaris


Uma das maiores vantagens de usar classes para organizar dados é que as instâncias têm a garantia de ter os atributos que você espera. Todas as instâncias de `Dog` têm os atributos `.species`, `.name` e `.age`, então você pode usar esses atributos com confiança, sabendo que eles sempre retornarão um valor.

Embora seja garantido que os atributos existam, seus valores podem mudar dinamicamente:

In [14]:
buddy.age = 10
print(buddy.age)
miles.species = "Felis silvestris"
print(miles.species)

10
Felis silvestris


Neste exemplo, alteramos o atributo `.age` do objeto `buddy` para `10`. Em seguida, alteramos o atributo `.species` do objeto `miles` para `"Felis silvestris"`, que é uma espécie de gato. Isso torna `Miles` um cachorro bem estranho, mas é um Python válido!

A principal lição aqui é que objetos personalizados são mutáveis ​​por padrão. Um objeto é mutável se você puder alterá-lo dinamicamente. Por exemplo, listas e dicionários são mutáveis, mas strings e tuplas são imutáveis.

### 8.7. Métodos de Instância

Métodos de instância são funções que você define dentro de uma classe e só podem ser chamadas em uma instância dessa classe. Assim como `.__init__()`, um método de instância sempre recebe `self` como seu primeiro parâmetro.

In [16]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    # Método de instância
    def description(self):
        return f"{self.name} is {self.age} years old"

    # Outro método de instância
    def speak(self, sound):
        return f"{self.name} says {sound}"

Esta classe `Dog` possui dois métodos de instância:

- `.description()` retorna uma string exibindo o nome e a idade do cachorro.

- `.speak()` possui um parâmetro chamado `sound` e retorna uma string contendo o nome do cachorro e o som que ele emite.

Vamos ver os métodos de instância em ação:

In [18]:
miles = Dog("Miles", 4)
print(miles.description())
print(miles.speak("Woof Woof"))
print(miles.speak("Bow Wow"))

Miles is 4 years old
Miles says Woof Woof
Miles says Bow Wow


Na classe `Dog` acima, `.description()` retorna uma string contendo informações sobre a instância de `Dog`, `miles`. Ao escrever suas próprias classes, é uma boa ideia ter um método que retorne uma string contendo informações úteis sobre uma instância da classe. No entanto, `.description()` não é a maneira mais Pythonica de fazer isso.

Ao criar um objeto de lista, você pode usar `print()` para exibir uma string que se parece com a lista:

In [19]:
names = ["Miles", "Buddy", "Jack"]
print(names)

['Miles', 'Buddy', 'Jack']


Vamos em frente tentar imprir o objeto `miles` para ver qual saída obtemos:

In [20]:
print(miles)

Ao imprimir `miles`, você recebe uma mensagem aparentemente enigmática informando que `miles` é um objeto `Dog` no endereço de memória `0x106d12bd0`. Esta mensagem não é muito útil. Você pode alterar o que é impresso definindo um método de instância especial chamado `.__str__()`.

Vamos alterar o nome do método `.description()` da classe `Dog` para `.__str__()`:

In [21]:
class Dog:
    species = "Canis familiaris"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    # Instance method
    def __str__(self):
        return f"{self.name} is {self.age} years old"

    # Another instance method
    def speak(self, sound):
        return f"{self.name} says {sound}"

Agora, vejamos o que acontece quando tentamos imprimir `miles`:

In [22]:
miles = Dog("Miles", 4)
print(miles)

Miles is 4 years old


Métodos como `.__init__()` e `.__str__()` são chamados de métodos `"dunder"` porque começam e terminam com dois sublinhados. Existem muitos métodos `"dunder"` que você pode usar para personalizar classes em Python. Entender os métodos `"dunder"` é uma parte importante do domínio da programação orientada a objetos em Python.

### 8.8. Herança

Herança é o processo pelo qual uma classe assume os atributos e métodos de outra. Classes recém-formadas são chamadas de **classes filhas**, e as classes das quais você deriva classes filhas são chamadas de **classes pais**.

Você herda de uma classe pai criando uma nova classe e colocando o nome da classe pai entre parênteses:

In [ ]:
class Animal:

    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def __str__(self):
        return f"{self.name} is {self.age} years old"

class Dog(Animal):
    def __init__(self, name, age, race):
        super().__init__(name, age)
        self.race = race
    
    def speak(self, sound):
        return f"{self.name} says {sound}"

Nesse exemplo, a classe `Dog` (filha) herda da classe `Animal` (pai). `Dog` herda os atributos `.name` e `.age` e o método `.__str__()` de `Animal`. Observe que no contrutor de `Dog`, o método especial `supper()` é invovado. Isso permite fazer uma refer6encia à classe pai e, no caso em questão, invocar o contrutor da classe pai passando como argumento o nome e a idade do cachorro (`super()__init__(name, age)`).

Agora, vamos explorar o resultado:

In [28]:
miles = Dog("Miles", 4, "Labrador")
print(miles)
print(miles.speak("Woof Woof"))
print(miles.race)

Miles is 4 years old
Miles says Woof Woof
Labrador


### 8.9. Exercícios

In [ ]:
# Esta célula informa ao Jupyter para fornecer informações detalhadas de depuração
# quando ocorrer um erro de execução. Execute-o antes de trabalhar nos exercícios.

%xmode Verbose

#### 8.9.1. Exercício

Neste exercício você vai implementar um pequeno sistema bancário usando os conceitos de OO. Abaixo você vê a implementação da classe `Conta` que representa uma conta bancária no nosso sistema:

```python
class Conta:
    def __init__(self, numero):
        self.__numero = numero
        self.__saldo = 0.0

    def creditar(self, valor):
        self.__saldo += valor
   
    def debitar(self, valor):
        self.__saldo -= valor
   
    def get_numero(self):
        return self.__numero 
   
    def get_saldo(self):
        return self.__saldo
```

Considere a implementação parcial da classe `Banco` abaixo:

```python
class Banco:
    def __init__(self):
        self.__contas = []

    def cadastrar(self, conta):
        self.__contas.append(conta)

    def procurar(self, numero):
        for conta in self.__contas:
            if conta.get_numero() == numero:
                return conta
        return None

    def creditar(self, numero, valor):
        conta = self.procurar(numero)
        if conta is not None:
            conta.creditar(valor)

    def debitar(self, numero, valor):
        pass
   
    def get_saldo(self, numero):
        pass
   
    def transferir(self, origem, destino, valor):
        pass
```

Agora, crie um módulos chamado `sisbanco.py` e codifique as classes `Conta`e `Banco` provendo a implementação dos métodos `debitar(...)`, `get_saldo(...)` e `transferir(...)`.


In [30]:
from sisbanco import Conta, Banco

banco = Banco()

conta = Conta('123-X')
banco.cadastrar(conta)

conta = Conta('234-X')
banco.cadastrar(conta)

banco.creditar('123-X', 500)
print('123-X: saldo', banco.get_saldo('123-X'))
print('234-X: saldo', banco.get_saldo('234-X'))

banco.debitar('123-X', 100)
print('123-X: saldo', banco.get_saldo('123-X'))

banco.transferir('123-X', '234-X', 300)
print('123-X: saldo', banco.get_saldo('123-X'))
print('234-X: saldo', banco.get_saldo('234-X'))

123-X: saldo 500.0
234-X: saldo 0.0
123-X: saldo 400.0
123-X: saldo 100.0
234-X: saldo 300.0


#### 8.9.2. Exercício

Agora, estenda a questão anterior que provenha a implementação da classe `Poupanca` com especificada abaixo dentro do módulo `sisbanco.py`:

```python
class Poupanca(Conta):
    def __init__(self, numero):
        super().__init__(numero)

    def render_juros(self, taxa): # o saldo da conta deve ser acrecido de saldo * taxa
        pass
```

Deve ser codificado o seguinte método na classe `Banco` para permitir aplicar a taxa de correção da poupança:

```python
class Banco:
    (...)
   def render_juros(self, numero, taxa):
        conta = self.procurar(numero)
        if conta not None:
            if isinstance(conta, Poupanca): #verifica se conta é uma sintância de `Poupanca`
                conta.render_juros(taxa)
```


In [2]:
from sisbanco import Banco, Poupanca

banco = Banco()

popupana = Poupanca('345-X')
banco.cadastrar(popupana)
print('345-X: saldo',banco.get_saldo('345-X'))

banco.creditar('345-X', 1000)
print('345-X: saldo',banco.get_saldo('345-X'))

banco.render_juros('345-X', 0.01)
print('345-X: saldo',banco.get_saldo('345-X'))

345-X: saldo 0.0
345-X: saldo 1000.0
345-X: saldo 1010.0
